# General Theoretical Background

The implementation and assessment of an Emotion Awareness Tool (EAT) in distance learning covers a wide spectrum of theories, pertaining often to multi- or inter-disciplinary fields. A comprehensive review of all the relevant literature is therefore beyond the scope and reach of the thesis. The general theoretical background will thus be preeminently tailored around the three elements that compose the acronym EAT: Emotion, Awareness and Tool. 

First, an EAT targets an *emotion* as the affective phenomenon of interest. It is therefore necessary to define what an emotion is, as well as mechanisms determining -- at the intra- and inter-personal levels -- causes and consequences of emotions, in particular with respect to learning processes. The section about emotion will mainly draw information from psychological theories of emotions, as well as contributions targeting the interplay between affective states and learning.

Second, an EAT is supposed to provide *awareness* to its users. Awareness is a multi-faceted concepts, which can be roughly mapped to two distinct -- but possibly intertwined -- phenomenon. On the one hand, intra-personal awareness: the mechanism by which a person becomes aware of something. On the other hand, inter-personal awareness, that is, the perception, processing and use of information about others. The section about awareness will focus mainly on the latter, drawing from the literature about the importance and instrumentality of information about others in a computer-mediated environments, which requires alternative channels of communication with respect to face-to-face conditions. 

Third, an EAT is a *tool*, that is, a computational and information system implemented in a technology enhanced environment. It must therefore resolve, for instance, what kind of entities are targeted as input, when and how they are inserted into the system, as well as how and when these entities are then mapped to corresponding outputs, with various possible degrees of processing in between. The more technical section of the theoretical framework will mainly draw from the literature about affective systems -- such as affect-aware or emotion-aware systems -- implemented in learning environments. 

The theoretical framework will also consider some pivotal aspects of distance learning, especially in terms of learners' needs. Even though there is a growing consensus in considering that the frontiers between distance and co-located education are progressively falling apart, there is also ample evidence for the need to adapt the instructional design according to the conditions in which learning processes take place. The cognitive, social, and affective determinants of learning are situated and interact with the environment. As a consequence, there are fundamental differences whether learners' share both, either, or none of the spatial and temporal coordinates. 

Finally, the chapter will illustrate and discuss some key contributions in the literature, which have investigated emotional awareness with theoretical, methodological, or instrumental perspectives that are relevant to the thesis. These contributions will be referred to -- by comparison and contrast -- in the empirical chapters of the thesis, and it is therefore worth illustrating them at length. 

## Emotion

### From What An Emotion Is To What An Emotion Does

*What is an emotion?* is a question that appears as a label in various types of contributions related to emotions. Foremost, it is the title of a seminal article by William James [-@jamesWhatEmotion1884], which, despite being more than a century old, is still source of lively debate [@ellsworthWilliamJamesEmotion1994; @schererWhatAreEmotions2005]. There are many iconic statements that testify to the difficulty of studying emotions from a scientific perspective. Fehr and Russel [-@fehrConceptEmotionViewed1984, p. 464] argued that "[e]veryone knows what an emotion is, until asked to give a definition", which resonates with Kleinginna and Kleinginna [-@kleinginnaCategorizedListEmotion1981], who, around the same time forty years ago, collected almost one hundred definitions. More recently, Frijda and Scherer [@frijdaEmotionDefinitionsPsychological2009, p. 142] still confirmed that "emotion may be one of the fuzziest concepts in all of the sciences", which has nevertheless not stopped scholars to study it from different -- sometimes converging, oftentimes diverging -- perspectives [for a recent overview, see among others @adolphsNeuroscienceEmotionNew2018; @deonnaEmotionsPhilosophicalIntroduction2012; @dixonPassionsEmotionsCreation2003; @foxNatureEmotionFundamental2018; @oatleyEmotionsBriefHistory2004; @plamperHistoryEmotionsIntroduction2015; @pekrunEmotionsSchool2018]. On the contrary, and possibly as a consequence, within the social sciences alone, the number of publications with the keyword *emotion* has annually multiplied by a factor of 1.13 between 1990 and 2011 [@schererHumanEmotionExperiences2013].

Issues about the definition of emotion are rooted in historical, cultural and epistemological differences, within and across disciplines and approaches (see for example @dixonPassionsEmotionsCreation2003 and @plamperHistoryEmotionsIntroduction2015 for overarching perspectives, or @sanderModelsEmotionAffective2013 for a more concise introduction). A synthesis that may be of interest and support in the present contribution identifies three aspects which are problematic in the definition of emotion, and that will be addressed more specifically in the reminder of the whole chapter. First, the relationship and discrimination between emotion and other affect-related phenomena such as preferences, attitudes, moods, affective dispositions, and the like [@schererWhatAreEmotions2005]. For instance, Pekrun and Linnerbrink-Garcia (2014, p. 2) highlight that “[i]n the broader education literature, affect is often used to denote a broad variety of noncognitive constructs including emotion but also including self-concept, beliefs, motivation, and so on". Second, a *bounding* problem in determining what can be considered part of the emotion, and what pertains to antecedents and consequences. For instance, there are different theories of emotion causation [@moorsTheoriesEmotionCausation2009; @sanderModelsEmotionAffective2013] and different theories that deals with the aftermath of an emotion, such as emotion regulation [@fischerSocialFunctionsEmotion2016; @grossHandbookEmotionRegulation2014; @zakiInterpersonalEmotionRegulation2013] or the impact of emotions on cognition and behavior [@becharaRoleEmotionDecisionmaking2004; @broschImpactEmotionPerception2013]. Finally, emotion may vary also as a function of the level of analysis. Some disciplines or contributions focus exclusively on one, or combine more of these aspects: (1) the emotional state *per se*, existing above and beyond the organism that is experiencing it [@adolphsNeuroscienceEmotionNew2018];  (2) the conscious experience that derives from an emotion, that is, what philosophers may refer to as *qualia* and psychologists as *feeling* [@grandjeanConsciousEmotionalExperience2008; @liebermanBooConsciousnessProblem2019; @schererWhatAreEmotions2005];  and (3) the various forms of representation and communication of emotions, both verbally and non-verbally [@fontaineComponentsEmotionalMeaning2013; @johnstoneVocalCommunicationEmotion2000; @scarantinoHowThingsEmotional2017; @torrePuttingFeelingsWords2018].

Despite the difficulties in finding a consensual definition of what an emotion is [@foxNatureEmotionFundamental2018; @sanderOxfordCompanionEmotion2009], a growing consensus has emerged over the last decades around a functional perspective on emotions. Rather than running aground on what an emotion is made of, for instance in terms of specific biological and physiological underpinnings, the focus shifts on what an emotion does [but see @godfrey-smithTrivialityArgumentsFunctionalism2009 for a critical point of view about functionalism]. In this regard, an hypothesis shared by many scholars posits that emotions have developed across species, for organisms to better adapt to a complex environment [@adolphsNeuroscienceEmotionNew2018; @darwinExpressionEmotionsMan1872; @deonnaEmotionsPhilosophicalIntroduction2012; @keltnerSocialFunctionsEmotions1999; @levensonIntrapersonalFunctionsEmotion1999; @leventhalRelationshipEmotionCognition1987; @schererEmotionProcessFunction1982; @damasioStrangeOrderThings2018]. Such a perspective has received interdisciplinary inputs, spanning from neuroscience to philosophy, and at different level of granularity: from the neurophysiological and preeminently intra-personal perspective [*e.g.*, @adolphsNeuroscienceEmotionNew2018; @levensonIntrapersonalFunctionsEmotion1999; @rollsEmotionDecisionmakingExplained2014] to the inter-personal role of emotions at the social and cultural levels [*e.g.*, @damasioStrangeOrderThings2018; @parkinsonEmotionSocialRelations2005; @rimePartageSocialEmotions2005; @plamperHistoryEmotionsIntroduction2015].

In a recent synthesis on the neuroscience of emotion, for instance, Adolphs and Anderson [-@adolphsNeuroscienceEmotionNew2018, p. 62] posit that emotions "should be thought of as adaptive functional states that are at the level of complexity intermediate between reflexes and volitional deliberation or calculation". The authors suggest that this intermediate level of complexity emerges from properties of emotions that can roughly be placed on a continuum between *building-blocks* on the one side, and *features* on the other. Building-blocks are considered as properties of emotions that are essential -- for instance, by being shared across species -- whereas features are more elaborate characteristics that have evolved only in specific species and contexts. As examples of building-blocks, the authors suggest *valence* and *persistence*. In the case of valence, in fact, most theories of emotion across disciplines consider that emotions are related to an evaluation of the situation as pleasant or unpleasant, even though valence can be interpreted in different ways [*e.g.*,@colombettiAppraisingValence2009; @erbasRoleValenceFocus2015; @schererNatureDynamicsRelevance2013; @shumanLevelsValence2013]. Persistence, on the other hand, refers to the mechanism by which an emotion spans over a few seconds to minutes, giving thus the time to te organism to process and integrate the information, but also to modify the current state in light of new information [@butlerEmotionsAreTemporal2017; @schererEmotionProcessFunction1982]. On the opposite side of the continuum, Adolphs and Anderson (*ibid.*) place features such as *automaticity* and *social communication*. Automaticity refers to the fact that emotions are often bestowed precedence over deliberate volition, for instance in the perception of stimuli [*e.g*, @broschPerceptionCategorisationEmotional2010; @poolAttentionalBiasPositive2015], and therefore require regulatory efforts, especially in human beings [@grossEmotionRegulationCurrent2015; @grossHandbookEmotionRegulation2014]. Social communication relates to the presence of efferent manifestations -- which can be more or less articulated and detectable across sensory modalities -- that signal the emotional states in others, and can therefore be perceived and processed as valuable information [@darwinExpressionEmotionsMan1872; @mehuPsychoethologicalApproachSocial2012; @mumenthalerSocialAppraisalInfluences2012; @vankleefHowEmotionsRegulate2009].

The social and cultural function of emotion may therefore have been built upon a *feature* that has evolved particularly in some species, such as human beings, for which inter-personal relations are pivotal to survival and, less dramatically, well-being [@parkinsonEmotionSocialRelations2005; @rimePartageSocialEmotions2005; @vankleefInterpersonalDynamicsEmotion2018; @keltnerSocialFunctionsEmotions1999]. Keltner and Haidt [-@keltnerSocialFunctionsEmotions1999] identify four level of analysis in which emotion play a social function: (1) the individual level, whenever the source of the emotion is of a social nature -- which, for some scholars, means most if not all of the time [@fischerWhereHaveAll2010; @parkinsonEmotionsAreSocial1996; @rimeEmotionElicitsSocial2009]; (2) the dyadic level, such as in direct dialogue or collaboration; (3) the group-level, in which people share a common identities and goals to attain; and (4) the cultural level, where the analysis focus on macro-elements such as history and tradition. A recent overarching synthesis on the social function of emotions across all levels proposed by Fischer and Manstead [-@fischerSocialFunctionsEmotion2016] identifies two complementary, but distinct, functions performed by emotions: affiliation, and distancing. The affiliation function serves to form and maintain positive social relationship with others, whereas the distancing function helps in establishing and maintaining a social position relative to others. Other social functions of emotions, further developed below in the chapter, comprise the spontaneous tendency of people to share their emotions with others [@rimeEmotionElicitsSocial2009; @rimePartageSocialEmotions2005], the use of emotional information to better understand behavior and appropriate conduct in social situations [@parkinsonEmotionsInterpersonalInteractions2010; @vankleefHowEmotionsRegulate2009], or situation in which people voluntary attempt to act upon emotions in others [@netzerInterpersonalInstrumentalEmotion2015; @reeckSocialRegulationEmotion2016; @zakiInterpersonalEmotionRegulation2013].

The overall picture depicted by an apparently simple question, *what is an emotion?*, uncovers a multifaceted concept that has been tackled from different perspectives. Considering that an EAT such as the one briefly illustrated in the Introduction aims at taking advantage of the *full* complexity of emotion, this subsections highlights some major points. First, from a theory-driven perspective, it is important to state clearly what model of emotion is considered. Second, an EAT must deal with both the intra- and inter-personal functions of emotions, and it should thus preferably find a unitary -- or at least integrative -- rather than a piecemeal approach. In this intent, the next subsection illustrates some candidates models drawn from psychological theories of emotion.

### Psychological Theories of Emotions



### Appraisal Theories of Emotions

### The Component Process Model Theoretical Framework

### Intra-Personal Functions of Emotion

### Inter-Personal Functions of Emotion

### Emotion and Learning

## Awareness

### Intra-Personal Awareness

### Inter-Personal Awareness

### Awareness Tools in Computer-Mediated Environments

### Emotional Awareness in Computer-Mediated Environments

## Affective Systems 

### Affective Computing

### Computational Models of Emotions

### Affective Systems in Learning Environments

### Affordance

## Distance Learning

### Synchronous vs. Asynchrounous Distance Learning

### Individual vs. Collaborative Distance Learning

## Illustration and Discussion of Key Contributions

### Emotion Understanding and Performance During Computer-Supported Collaboration

### Emotion Feedback During Computer-Mediated Collaboration

### Towards Emotion Awareness Tools to Support Emotion and Appraisal Regulation in Academic Contexts

## Summary