---
bibliography: references.bib
---

# Introduction {#general-introduction .unnumbered}

```{r intro-setup, include=FALSE, echo=FALSE}
library(tidyverse)
library(papaja)
library(here)
library(knitr)
library(kableExtra)

```

Imagine that you are co-authoring a text with a colleague for an upcoming assignment that you must submit in a course: you are at home, she can be anywhere in the world. You are using an online text processor, which allows you to edit the document simultaneously. This particular text editor has the feature of attributing animal names to authors, so that you are currently identified in the work-space as *anonymous hippo*, and your partner is *anonymous turtle*. The only thing you can see about the *turtle* is the flow of letters that stems from the position of her cursor in the document whenever she is typing on her keyboard, and *vice versa*. Imagine being in this situation: what kind of information about the *turtle* would you like to know to better assess how the learning task is going? And what kind of information about yourself would you like the *turtle* to know, for her to better assess how the learning task is going?

Now imagine that you are coding a project in an introductory programming course: you are facing lines of condensed and often mysterious syntax, whose execution sometimes results in the desired and celebrated outcome, but oftentimes leads to irking and obscure message errors. You are alone in front of your screen -- riddled with software you barely know and dozens of tabs in your browsers with results to hazardous research queries -- wondering whether your colleagues in the course are facing a similar fate. What information about them would help you better cope with this situation? What information about yourself would you like to share, which could be beneficial both to you and them?

You have certainly guessed from the title of the thesis that the answer put forward to these questions is: *emotions*. In the last few decades, emotions have been widely studied from different perspectives and with different methods, giving rise to the interdisciplinary field of affective sciences [e.g., @davidsonHandbookAffectiveSciences2003; @sanderOxfordCompanionEmotion2009]. A consistent body of research has corroborated the importance that affective phenomena -- such as emotions, feelings, motivations, moods, or preferences -- play in various circumstances of life, both individually and collectively, and at different levels of processing [@adolphsNeuroscienceEmotionNew2018; @armonyCambridgeHandbookHuman2013; @barrettHowEmotionsAre2018; @colombettiFeelingBodyAffective2014; @damasioStrangeOrderThings2018; @fischerSocialFunctionsEmotion2016; @fontaineComponentsEmotionalMeaning2013; @pessoaCognitiveemotionalBrainInteractions2013; @rimePartageSocialEmotions2005; @sanderModelsEmotionAffective2013; @vankleefInterpersonalDynamicsEmotion2018]. As a consequence of that, leading scholars in the field [@dukesRiseAffectivism2021] have recently considered legitimate to ask whether research has entered a new era: the era of *affectivism*.

> The conceptual, methodological, and technical advances made within the last few decades have demonstrated that affective processes are unquestionably enlightening when it comes to understanding both behaviour and cognition. While it will ultimately be the responsibility of historians of science to determine whether or not a new era has begun, given the undeniable impact of affective sciences on our models of brain, mind, and behaviour, it seems relevant to ask today whether we are now in the era of affectivism.\
> --- @dukesRiseAffectivism2021, p. 819

Even though *affectivism* may have taken more time to take on in learning and education sciences [@pekrunInternationalHandbookEmotions2014; @pekrunProgressOpenProblems2005], there is nowadays a growing consensus in considering learning as the results of cognitive, social, and affective interactions [@bakerAffectiveLearningTogether2013; @immordino-yangEmotionsLearningBrain2016; @brackettPermissionFeelUnlocking2019; @pekrunInternationalHandbookEmotions2014; @pekrunEmotionsSchool2018]. With respect to the role of affective phenomena more specifically, three intertwined research areas can be discerned. First, research investigating the effect of learning and teaching activities on learners' and teachers' affective experience [@dmelloSelectiveMetaanalysisRelative2013; @pekrunControlValueTheoryAchievement2006; @pekrunIntroductionEmotionsEducation2014]. Second, research that, conversely, focuses on the effect of affective phenomena on learning processes and outcomes [@dmelloConfusionCanBe2014; @hascherLearningEmotionPerspectives2010; @immordino-yangEmotionsLearningBrain2016]. Third, research that investigates the existence of social and emotional competences that may be beneficial inside and outside learning contexts, and how to empower learners with those competences [@brackettPermissionFeelUnlocking2019; @brackettRULERTheoryDrivenSystemic2019; @jarvelaSociallySharedRegulation2016; @winneWhatStateArt2015].

The role of affective phenomena in general, and emotions more specifically, is particularly challenging in computer-mediated learning environments -- a term used throughout the text to encompass, at least partially, concepts such as advanced learning technologies [@graesserEvolutionAdvancedLearning2013]; computer-based learning environments [@moosLearningComputerBasedLearning2009]; computer-supported collaborative learning [@dillenbourgEvolutionResearchComputersupported2009]; distance, remote or e-learning [@bates2005technology]; and technology enhanced learning [@kirkwoodTechnologyenhancedLearningTeaching2014]. The role of computational devices in both formal and informal education has become ubiquitous, especially in higher education, and a growing body of research is therefore devoted to investigate the interplay between affective phenomena and computer-mediated learning environments [@arguedasOntologyEmotionAwareness2015; @cerneaSurveyTechnologiesRise2015; @dmelloFeelingThinkingComputing2015; @feidakisReviewEmotionAwareSystems2016; @graesserEmotionsAdvancedLearning2014; @harleyDevelopingEmotionAwareAdvanced2017].

In this regard, part of the literature on the subject highlights shortcomings in computer-mediated learning environments due to the lack of para-verbal cues, usually available in non-mediated face-to-face interactions, which play a prominent role in various aspects of learning such as coordination, communication, sense of belonging or inter-subjective meaning-making [@marchandRoleEmotionLearning2012; @michinovFacetofaceContactMidpoint2008; @kreijnsIdentifyingPitfallsSocial2003; @kreijnsSocialAspectsCSCL2013; @dillenbourgSymmetryPartnerModelling2016]. In fact, even in co-located settings, the presence of a computer captures and directs learners' attention [@eligioEmotionUnderstandingPerformance2012], and therefore reduce the availability of cues, such as facial expressions or body postures, that are well known to convey emotional meaning [@banzigerEmotionRecognitionExpressions2009; @martinezContributionsFacialExpressions2016; @schererInvestigatingAppraisaldrivenFacial2019; @shumanEmotionPerceptionComponential2017]. These shortcomings are further accentuated in distance learning, especially in asynchronous settings, where learners do not interact in real time, but have to cope with latency time and delayed exchanges [@bates2005technology; @jacquinotApprivoiserDistanceSupprimer1993; @paquelinDistanceQuestionsProximites2011]. There is a growing consensus in considering that such situations may benefit from some form of *social presence*, that is, the perception of others in the absence of *physical* presence [@gunawardenaSocialPresencePredictor1997; @jezegouCreerPresenceDistance2010; @lowenthalSearchBetterUnderstanding2017]. In this regard, several contributions highlight the importance of affective phenomena in providing a holistic experience of this social presence [@jezegouCreerPresenceDistance2010; @lowenthalSearchBetterUnderstanding2017; @rourkeLearningCommunitiesInquiry2009; @kirschnerAwarenessCognitiveSocial2015].

In the meantime, the literature also suggests that human beings' need for experiencing and expressing emotions transcends time and space [@derksRoleEmotionComputermediated2008; @parkinsonEmotionsDirectRemote2008; @rimePartageSocialEmotions2005; @vankleefSocialEffectsEmotions2017]. In this regard, the use of computers may provide alternatives, or even enhance emotional experience and communication, through dedicated or integrated artifacts [@boehnerHowEmotionMade2007; @derksRoleEmotionComputermediated2008; @parkinsonEmotionsDirectRemote2008; @vankleefSocialEffectsEmotions2017]. In other words, face-to-face interaction may not necessarily be considered as the golden standard to re-enact, for instance, by providing seamless audio/video connection [@buderGroupAwarenessTools2011; @janssenCoordinatedComputerSupportedCollaborative2013]. On the contrary, emotion in computer-mediated learning environments may be conveyed through a wide panel of options, ranging from *simple* emoticons to autonomic recognition and representation through dedicated hardware and software [@arguedasModelProvidingEmotion2018; @baralouEmotionsSpatialisationSocial2013; @gliksonDarkSideSmiley2018; @graesserEmotionsAdvancedLearning2014; @harleyDevelopingEmotionAwareAdvanced2017; @cerneaSurveyTechnologiesRise2015]. Computational devices open a wide spectrum of possibilities in the cycle of input, processing, and output of emotional information, including various means to gather data, persistence of data over time, visual-spatial displaying of data, as well as technologies that react or adapt based on learners' affective experience [@arguedasModelProvidingEmotion2018; @cerneaGroupAffectiveTone2014; @dmelloFeelingThinkingComputing2015; @grawemeyerAffectiveLearningImproving2017; @kimRoleAffectiveMotivational2012; @leonyProvisionAwarenessLearners2013; @fuentesSystematicLiteratureReview2017; @silvaComparativeStudyUsers2020].

The choice of how to endow the computer-mediated learning environment with affect-related information and the reasons to do so depends on various criteria, with pedagogical and technical aspects often intertwined in mutual influence. In this regard, a growing body of research in the last decade has started to investigate the possibility to endow computer-mediated learning environments with emotional awareness, which is roughly defined as information about one's own emotions and/or about the emotions of other learners sharing the same computer-mediated learning environment [@arguedasOntologyEmotionAwareness2015; @avrySharingEmotionsContributes2020; @cerneaSurveyTechnologiesRise2015; @dmelloFeelingThinkingComputing2015; @eligioEmotionUnderstandingPerformance2012; @lavoueEmotionAwarenessTools2020; @molinariEmotionFeedbackComputermediated2013]. Contributions pertaining to this line of inquiry explicitly or implicitly share one ore more of the following underlying assumptions. First, it is posited that learners may benefit from being aware of their own emotions, that is, that their own emotions provide instrumental information for self-regulation of learning [@ez-zaouiaEmodashDashboardSupporting2020; @lavoueEmotionAwarenessTools2020; @molinariEMORELOutilReporting2016; @winneWhatStateArt2015]. Second, it is assumed that emotion may convey instrumental information to others, for them to integrate that information into their own learning task, as a means to improve self-regulation, co-regulation and social regulation of learning [@eligioEmotionUnderstandingPerformance2012; @molinariEmotionFeedbackComputermediated2013; @winneWhatStateArt2015; @jarvelaSociallySharedRegulation2016; @jarvelaEnhancingSociallyShared2015]. Third, it is also implied that emotion can be fruitfully conveyed in a computer-mediated learning environment, that is, the emotional information is made available and processed by users in the learning environment where learning activity and emotional awareness coexist in some form [@bersetVisualisationDonneesRecherche2018; @cerneaSurveyTechnologiesRise2015; @leonyProvisionAwarenessLearners2013; @harleyMeasuringEmotionsSurvey2015; @fuentesSystematicLiteratureReview2017].

One way for learning activity and emotional awareness to coexist is through the use of an Emotion Awareness Tool (EAT). An EAT coalesces features of affect- or emotion-aware systems on the one side, and of awareness tools on the other. Affect- or emotion-aware systems [@calvoFeelingThinkingComputing2015; @graesserEmotionsAdvancedLearning2014; @grawemeyerAffectiveLearningImproving2017; @harleyDevelopingEmotionAwareAdvanced2017] stem mainly from the interdisciplinary field of affective computing [@picardAffectiveComputing2000; @schererBlueprintAffectiveComputing2010] and are therefore driven, *in primis*, by computational modeling of affective phenomena [@marsellaComputationalModelsEmotion2010; @schererComponentProcessModel2010]. Awareness tools [@buderGroupAwarenessTools2011; @janssenCoordinatedComputerSupportedCollaborative2013; @janssenGroupAwarenessTools2011], on the other hand, emerged primarily from the field of computer-mediated collaboration and were later implemented in computer-mediated learning environments, especially through the interdisciplinary field of Computer-Supported Collaborative Learning [@dillenbourgEvolutionResearchComputersupported2009; @kreijnsSocialAspectsCSCL2013; @millerScriptingAwarenessTools2015; @suthersTechnologyAffordancesIntersubjective2006]. Awareness tools have thus an intrinsic inter-personal stance, which emphasizes learners' need to build and update a mutual understanding of the situation at hand [@clarkGroundingCommunication1991; @roschelleConstructionSharedKnowledge1995] as a means to maximize inter-subjective meaning-making, considered as a determinant of learning processes and outcomes [@dillenbourgSymmetryPartnerModelling2016; @janssenCoordinatedComputerSupportedCollaborative2013; @janssenGroupAwarenessTools2011; @suthersTechnologyAffordancesIntersubjective2006].

It follows that an EAT is a technological artifact, whose aim is to provide learners with emotional awareness in computer-mediated learning environments, under the assumption that its availability is beneficial to learners at the individual and/or collective levels [@arguedasAnalyzingHowEmotion2016; @avryAchievementAppraisalsEmotions2020; @avrySharingEmotionsContributes2020; @cerneaSurveyTechnologiesRise2015; @feidakisEndowingElearningSystems2011; @lavoueEmotionAwarenessTools2020; @molinariEmotionFeedbackComputermediated2013]. Such a claim has received in the last decade an increasing interest in the affective, computer, and learning sciences from different theoretical, technical, methodological and empirical standpoints (*ibid.*). Applications of an EAT in computer-mediated learning environments may in fact range from providing learners with the possibility to self-report their emotions during a distance learning course as a means to increase self-reflection and self-regulation [@lavoueEmotionalDataCollection2017] to the implementation of a multi-modal system that provide emotional awareness through an unobtrusive brain-computer interface during computer-mediated collaboration [@makhkamovaAugmentingCollaborationInvisible2019]. Despite the differences in application, though, research gravitating around an EAT usually aims at investigating which factors -- intrinsic to the tool, deriving from the interaction between learners and the tool, between learners themselves, as well as between learners and the instructional design -- determine whether and how emotional awareness may be beneficial in computer-mediated learning environments.

The thesis aims at extending this area of investigation by implementing and assessing a multipurpose, appraisal-driven emotion awareness tool based on self-reported emotions, which learners may express and perceive voluntarily and at any time while performing learning-oriented tasks in a computer-mediated environment. The implemented tool is also adopted -- in an iterative interaction design and user-centered perspective [@rogersInterctionDesignHumanComputer2011; @cooperFaceEssentialInteraction2007; @lallemandMethodesDesignUX2017] -- in three empirical contributions, which are meant to investigate specific research questions, and at the same time inform the development of the EAT. In the reminder of this introduction, these intertwined objectives are first put into the general perspective adopted by the thesis. They are then specified individually in two sections that outline the methodological and empirical contributions respectively. The introduction ends with the outline of the manuscript, and with references to code and data, both of the implemented EAT and the computational manuscript of the whole thesis, which are made publicly available [@levensteinDataSharingCaring2018; @gilmorePracticalSolutionsSharing2018].

## Thesis Perspective {.unnumbered}

In the last few years, psychology has faced what has been widely referred to as the replication crisis [@earpReplicationFalsificationCrisis2015; @anvariReplicabilityCrisisPublic2019; @chambersSevenDeadlySins2017; @opensciencecollaborationEstimatingReproducibilityPsychological2015]. What started as primarily a problem of statistical practices and inferences that undermined the reliability of experiments' results [@opensciencecollaborationEstimatingReproducibilityPsychological2015; @cassidy2019; @nuijten2016; @benjaminRedefineStatisticalSignificance2018; @lakensJustifyYourAlpha2018] quickly turned in a wider methodological assessment of psychology's theories and overall practices [@chambersSevenDeadlySins2017; @scheel2020; @mcphetres2021; @makelQuestionableOpenResearch2019; @johnMeasuringPrevalenceQuestionable2012]. The term *credibility crisis* is sometimes adopted to refer to this wider problematic, for which, often, solutions are identified as pertaining to four intertwined categories [@vazire2022; @shadishExperimentalQuasiexperimentalDesigns2002; @maxwellDesigningExperimentsAnalyzing2017]. First, construct validity, which broadly refers to how concept are defined and measured [@schererWhatAreEmotions2005; @shumanConceptsStructuresEmotions2014]. Second, internal validity, which relates to identifying potential causal mechanisms explaining or predicting phenomena of interest [@pearl2016; @pearl2000; @pearl2018; @rohrerThinkingClearlyCorrelations2018; @groszTabooExplicitCausal2020]. Third, external validity, that is how knowledge built in the *micro-world* of experiments can be generalized to the *macro-world* of interest [@yarkoniGeneralizabilityCrisis2022]. And, finally, statistical validity, which focuses on the link between domain knowledge and probability/statistical theory [@mcelreathStatisticalRethinkingBayesian2020; @rodgersEpistemologyMathematicalStatistical2010].

Given that the field of emotional awareness in computer-mediated learning environments is relatively recent and still requires refinement on theoretical, methodological, and technical grounds [@lavoueEmotionAwarenessTools2020; @lavoueEmotionalDataCollection2017; @molinariEmotionFeedbackComputermediated2013; @cerneaSurveyTechnologiesRise2015; @feidakis2016; @eligioEmotionUnderstandingPerformance2012], the thesis focuses primarily on construct and internal validity. The overall aim of the thesis can thus be divided in two intertwined objectives. On the one side, the methodological attempt to implement an EAT which maximizes the construct validity of emotional awareness. On the other side, the exploration of the internal validity of this same tool as an instrument that can be fruitfully implemented in empirical contributions investigating whether, how and why an EAT may be instrumental in computer-mediated learning environments. The two objectives are briefly outlined in the remainder of the section.

## Methodological Contribution {.unnumbered}

Alongside other scholars [@arguedasOntologyEmotionAwareness2015; @brackettRULERTheoryDrivenSystemic2019; @feidakisReviewEmotionAwareSystems2016; @harleyDevelopingEmotionAwareAdvanced2017; @lavoueEmotionAwarenessTools2020; @molinariEMORELOutilReporting2016], I reckon the way in which emotional awareness is implemented in a computer-mediated learning environment plays a prominent role in determining whether the EAT is adopted in the first place, and whether it serves its purpose in the wide spectrum of potential applications in which it may be deployed. Despite this variety, though, the role of an EAT may be broken down in two fundamental intertwined functions:

1.  Whether, when, why, and how emotional information is *inserted/encoded* into the computer-mediated learning environments through the EAT, creating thus the necessary -- but not sufficient -- conditions for emotional awareness to emerge. In awareness tools, this function refers to *displaying* information [@buderGroupAwarenessTools2011; @schmidtProblemAwareness2002] and is the equivalent of *expressing* emotion [@darwinExpressionEmotionsMan1872; @scarantinoHowThingsEmotional2017; @vankleefSocialEffectsEmotions2017] when applied to an EAT.
2.  Whether, when, why, and how emotional information is *retrieved/decoded* from the EAT and processed by learners, for emotional awareness to be enacted and hopefully contribute to learning processes and outcomes. In awareness tools, this relates to *monitoring* information [@buderGroupAwarenessTools2011; @schmidtProblemAwareness2002], which corresponds to *perceiving* or *recognizing* emotion [@hareliWhatEmotionalReactions2010; @schlegelNomologicalNetworkEmotion2017; @hallSocialPsychologyPerceiving2018] in the context of an EAT.

One of the central claim of the thesis is that both functions may be better served with the interaction of three factors: (1) voluntary self-report of emotion; (2) implementing an emotion structure into the tool; and (3) moment-to-moment availability of emotional awareness in the computer-mediated learning environment. Each factor is outlined hereafter.

### Voluntary Self-Report {.unnumbered}

I consider the opportunity that learners may best profit from emotional awareness through voluntary expression of their emotions [@fuentesSystematicLiteratureReview2017; @mortillaroEmotionsMethodsAssessment2015; @ritchieEvolutionSelfreportingMethods2016; @silvaComparativeStudyUsers2020], as opposed to automatic emotion detection [@jordivallverduHandbookResearchSynthesizing2015]. Self-report may encourage students to interpret, reflect on, extrapolate and construe meaning from emotion [@boehnerHowEmotionMade2007; @fontaineComponentsEmotionalMeaning2013; @lavoueEmotionAwarenessTools2020] in a more flexible and adaptable process compared to the automatic detection of predefined *matches* from uni- or multi-modal sources [@calvoAffectDetectionInterdisciplinary2010; @jordivallverduHandbookResearchSynthesizing2015].

### Implementing an Emotion Structure into the Tool {.unnumbered}

I evaluate the possibility that an EAT may best serve its purpose if its functioning is driven by emotion theories [@sanderModelsEmotionAffective2013; @sep-emotion; @moorsTheoriesEmotionCausation2009; @scarantinoPhilosophyEmotionsIts2018; @scherer2022; @foxNatureEmotionFundamental2018]. In this regard, the thesis builds on appraisal theories of emotion [@moorsAppraisalTheoriesEmotion2013; @rosemanAppraisalTheoryOverview2001; @schererWhatAreEmotions2005; @scherer2019], and more specifically the Component Process Model theoretical framework [@schererWhatAreEmotions2005; @schererDynamicArchitectureEmotion2009; @schererNatureDynamicsRelevance2013; @schererPredictionDataDriven2019]. The central tenet of the model consists in considering that emotion is elicited and differentiated through an ongoing evaluation of events against a set of criteria, named sequential evaluation checks. This cognitive evaluation, or appraisal, then produces a synchronized, bounded physiological and behavioral pattern that may eventually coalesce into a conscious representation of the whole emotional experience, the subjective feeling, which can be used for intra-individual and inter-individual symbolic representation (*ibid.*). One of the assumption stemming from the theory is that, if one knows how the situation has been appraised by a person, it is possible to approximate what kind of emotional experience she will go through, and how she will name it @schererHumanEmotionExperiences2013; @schererSemanticStructureEmotion2018; @schererSemanticStructureEmotion2019. This theoretical assumption is concretely implemented into the EAT through a parsimonious computational model, which, using an underlying affective space [@gilliozMappingEmotionTerms2016; @schererWhatDeterminesFeeling2006], bridges the cognitive evaluation of a situation and the resulting conscious emotional experience that learners may use for intra-personal and inter-personal emotion meaning-making [@grandjeanConsciousEmotionalExperience2008; @schererHumanEmotionExperiences2013]. Practically, the tool combines the dimensional and the discrete emotion approaches to emotion self-report [@mortillaroEmotionsMethodsAssessment2015; @schererWhatAreEmotions2005], which are dynamically linked by the probabilistic computational model. The result is an EAT that suggests the most likely subjective feelings to represent the emotional experience of a person, based on her rating on a set of appraisal dimensions [@fritzDynamicEmotionWheel2015; @fritzDynamicEmotionWheel2016; @fritzReinventingWheelEmotional2015; @fritzProvidingEmotionalAwareness2017]. It is argued that implementing an emotion structure in this way may maximize emotion self-reflection and production of a strategic signal that can be conveyed to others [@schererComponentialEmotionTheory2007], even through a computer-mediated environment [@vankleefSocialEffectsEmotions2017].

### Moment-to-Moment Availability of Emotional Awareness {.unnumbered}

Finally, I surmise that an EAT may increase its usefulness if learners are allowed to insert and retrieve emotional information at any moment [@graesserEmotionsAdvancedLearning2014; @molinariEmotionFeedbackComputermediated2013]. This refers to a distinction in instructional design between scripting and awareness tools [@millerScriptingAwarenessTools2015]. Within a scripting scenario, the learning activity is planned for learners to become aware of relevant information at specific and predefined moments [@dillenbourgOverscriptingCSCLRisks2002; @fischerScriptTheoryGuidance2013]. Conversely, awareness tools [@buderGroupAwarenessTools2011; @janssenCoordinatedComputerSupportedCollaborative2013] bestow learners with the responsibility of *producing and consuming* information at the very moment they see fit, either from an instrumental point of view (*I think this information is important right now*) or depending on the possibility to set their mind to it when coordinating multiple actions (*I can share or process this information now*). I argue that disposing of an EAT at any time in the computer-mediated learning environments may increase the chances of adopting it in the first place, but also to extrapolate meaning-making both at the intra-personal and inter-personal levels.

### Methodological Objectives {.unnumbered}

The methodological objectives of the thesis are twofold. First, provide detailed information about the implementation of an EAT where these three factors coalesce. To meet this objective, I build on and extend previous work conducted in the Emotion Awareness Tool for Computer-Mediated Interactions (EATMINT) project [@avryAchievementAppraisalsEmotions2020; @avrySharingEmotionsContributes2020; @cereghettiSharingEmotionsComputermediated2015; @Chanel2013; @chanelGrandChallengeProblem2016; @molinariEmotionFeedbackComputermediated2013]. More specifically, a prototype of an EAT named Dynamic Emotion Wheel [@fritzDynamicEmotionWheel2015], designed during an internship in the project and as the subject of my Master thesis [@fritzReinventingWheelEmotional2015], will serve as the basis for the implementation of a functioning proof of concept.

Second, building upon the core computational model of the EAT, I propose a toolbox intended for scholars and practitioners alike, for them to dispose of a ready-to-use instrument, without the need for dedicated hardware and with minimal software setup [@cerneaSurveyTechnologiesRise2015]. The toolbox allows the configuration of many aspects of the interface and inner functioning of the EAT, which may have theoretical, pedagogical and user-experience consequences. For instance, the toolbox provides the possibility to adopt different multi-dimensional affective spaces as the underlying structure of emotion [@fontaineWorldEmotionsNot2007; @gilliozMappingEmotionTerms2016; @russellCircumplexModelAffect1980; @schererWhatDeterminesFeeling2006]. This has as a consequence the possibility to chose which appraisal dimensions users will be asked to rate, as well as the number and kind of suggestions they will receive from the system. The options in configuring the EAT are also intended to increase comparability of research within the affective science and education technology domains, as well as encouraging sharing of data and material in open formats [@lowndesOurPathBetter2017; @scheelWhyHypothesisTesters2020; @schererWhatAreEmotions2005; @Nosek1422]. Furthermore, the toolbox will also allow to chose between some graphical representation of emotion [@leonyProvisionAwarenessLearners2013; @derickEvaluatingEmotionVisualizations2017; @bersetVisualisationDonneesRecherche2018; @fritzRealTimeEmotionalAwareness2016], which are meant to fulfill the perceiving-monitoring function of an awareness tool. This is the chance for researchers and scholars to decide how users will dispose of the emotional information inserted into the system, which, one again, may have important theoretical, pedagogical, and user-experience consequences.

To sum up, the methodological objectives of the thesis pertain to the implementation of a proof of concept, which aims at exploring whether an EAT with the aforementioned characteristics can be deployed and put at disposal of other scholars and practitioners interested in endowing computer-mediated environments with emotional awareness.

## Empirical Contribution {.unnumbered}

As mentioned above, the empirical contribution of the thesis mainly aim at exploring the internal validity of the implemented EAT as an instrument to investigate intervening factors when emotional awareness is at play. Alongside other scholars [@eligioEmotionUnderstandingPerformance2012; @lavoueEmotionAwarenessTools2020; @molinariEMORELOutilReporting2016; @avrySharingEmotionsContributes2020; @ruizSupportingLearningConsidering2016; @harleyDevelopingEmotionAwareAdvanced2017; @cerneaSurveyTechnologiesRise2015], I reckon that computer-mediated learning environments can benefit from emotional awareness, for learners to dispose of meaningful information that they can harness for self-regulation, co-regulation, or socially shared regulation of learning [@millerScriptingAwarenessTools2015; @jarvelaSociallySharedRegulation2016; @jarvelaEnhancingSociallyShared2015; @janssenCoordinatedComputerSupportedCollaborative2013; @jezegouCreerPresenceDistance2010].

In this regard, the thesis proposes three empirical contribution related to the use of the implemented EAT. The three studies are briefly outlined hereafter.

### Study 1 {.unnumbered}

Considerable research has been devoted in the last few decades on how collaboration may best be sustained when learners share the temporal but not the spatial dimension [@dillenbourgEvolutionResearchComputersupported2009; @jarvelaEnhancingSociallyShared2015; @kreijnsIdentifyingPitfallsSocial2003; @roschelleConstructionSharedKnowledge1995; @suthersTechnologyAffordancesIntersubjective2006]. It is nowadays widely accepted that one of the determinants of the quality of interaction, as well as learning processes and outcomes, consists in learners building and maintaining a holistic representation of each others in order to maximize mutual understanding, coordination, regulation and inter-subjective meaning-making [@dillenbourgSymmetryPartnerModelling2016; @janssenCoordinatedComputerSupportedCollaborative2013; @molinariKnowledgeInterdependencePartner2009; @jarvelaEnhancingSociallyShared2015]. More recently, some scholars have started to hypothesize that sharing emotions with the partner could, precisely, contribute to achieve this goal [@avrySharingEmotionsContributes2020; @eligioEmotionUnderstandingPerformance2012; @feidakisProvidingEmotionAwareness2014; @molinariEmotionFeedbackComputermediated2013]. The contributions investigating the matter have provided learners -- often divided in dyads -- with exactly the same emotional information: all the emotions shared by both learners, or none at all when using a control group without emotional awareness. When emotional awareness is provided, this ecological condition is consistent with the attempt to foster learners' mutual modeling, that is the act by which learners build and update a reciprocal holistic representation of what they are doing, thinking, or feeling [@dillenbourgSymmetryPartnerModelling2016; @sanginFacilitatingPeerKnowledge2011; @molinariKnowledgeInterdependencePartner2009; @engelmannKnowledgeAwarenessCSCL2009].

At a closer look, though, there are at least three intertwined -- but still distinct -- levels that may determine why a learner should consider to produce and peruse emotional information. First, the learner may be interested only in her own emotional experience. The fact of expressing how she feels may have benefit in terms of self-reflection and emotion self-regulation [@torrePuttingFeelingsWords2018; @levensonIntrapersonalFunctionsEmotion1999]. Second, the learner may be interested only in the emotions of the partners, and thus expressing her emotional experience is the reciprocal price to pay for everyone to dispose of this kind of information about others, which may be used as meaningful information for her own task [@fischerSocialFunctionsEmotion2016; @rimeEmotionElicitsSocial2009; @vankleefInterpersonalDynamicsEmotion2018]. Third, the learner may be in fact interested in the *full* mutual-modeling experience, with, for instance, the possibility to compare her own emotional experience with that of the partners [@eligioEmotionUnderstandingPerformance2012; @molinariEmotionFeedbackComputermediated2013; @avrySharingEmotionsContributes2020; @avryExplicitSharingEmotions2021]. The three situations incidentally coincide with the very definition of emotional awareness: information about one's own emotions and/or about the emotions of other learners. The first situation relates to the first part of the definition, whereas the second and third situation depends on the and/or distinction.

The first empirical contribution thus manipulate the interface of the EAT varying the use of and access to emotional information, under the assumption that this may change the concrete use of the EAT itself. In other words, learners will not produce and peruse emotional information at the same rate depending on what will be done of the emotion they express, and what emotional information they can access through the EAT. The three interfaces can in fact be placed on a scale which define how socially oriented they are, with the order of presentation reflecting the order of *social-orientation*. The underlying hypothesis states that the more socially-oriented is the interface, the greater use will be made of the EAT.

### Study 2 {.unnumbered}

As the recent events linked to the global pandemic have vividly purported, education cannot be transported *as-is* from the classroom to distance settings [@tecfaEnseignerDistanceDans2019]. This certainly came as no surprise for scholars that have widely investigated potentials and limitations of distance learning in the last decades [@bates2005technology; @jacquinotApprivoiserDistanceSupprimer1993; @jezegouCreerPresenceDistance2010; @paquelinDistanceQuestionsProximites2011; @sherryIssuesDistanceLearning1995]. A growing consensus has emerged about the need to attune the cognitive, pedagogical, and socio-affective dimensions in order to take advantage from distance learning and limit pitfalls, among which the sense of isolation resulting from the difficulty learners experience to connect with teachers or peers [@lowenthalSearchBetterUnderstanding2017; @jezegouCreerPresenceDistance2010].

There is a growing consensus in considering that affective phenomena can play a prominent role in determining the overall attitude of students in distance learning settings [@lavoué2020; @lavoué2017; @ez-zaouia2020; @jézégou2010; @lowenthalSearchBetterUnderstanding2017; @feidakisEndowingElearningSystems2011]. Even though emotion are nowadays considered by most scholars as short episodes elicited by specific events [@sanderModelsEmotionAffective2013; @schererWhatAreEmotions2005; @pekrunIntroductionEmotionsEducation2014], the cumulative emotional experience can have long lasting consequences on people's well-being and social interactions [@rimePartageSocialEmotions2005; @rimeEmotionElicitsSocial2009; @fischerSocialFunctionsEmotion2016; @parkinsonEmotionSocialRelations2005; @vankleefInterpersonalDynamicsEmotion2018]. Scholars have therefore started to follow the emotional experience of learners during longer periods of time under the assumption that emotions may foster reflection and self-regulation, but also helps in projecting students socially and affectively in asynchronous settings [@lavoueEmotionalDataCollection2017; @lavoueEmotionAwarenessTools2020; @ruizSupportingLearningConsidering2016; @jézégou2010; @lowenthalSearchBetterUnderstanding2017]

In the same vein, the use of an EAT will be implemented in two classes of a blended Master in education technology at Geneva University. Students will be using the EAT during the distance periods in an introductory course about computational thinking and web development, which does not include in the instructional design collaborative projects [@fritzPenseeComputationnelleAvec2019]. The longitudinal plan aims at investigating whether the EAT is adopted in the first place, and whether the perception of its usefulness changes over time [@fitzmauriceAppliedLongitudinalAnalysis2011]. The comparison between two different classes will also be the opportunity to explore whether the use of the EAT is mainly driven by individual attitudes, or whether some form of interaction may tight the individual use to the collective use [@dillenbourgSymmetryPartnerModelling2016; @janssenGroupAwarenessTools2011; @kirschnerAwarenessCognitiveSocial2015].

### Study 3 {.unnumbered}

The third empirical contribution takes advantage from the fact that the two previous ones have been conducted in very different settings: synchronous and collaborative the first, asynchronous and non-collaborative (or individual) the second. In the meantime, the toolbox was used to create instances of the tool who maintains a common *core*, which also happens to be the main characteristics of the EAT: self-report, computational model representing the emotion structure, and moment-to-moment availability.

The contribution thus combine data from both contributions and also from a previous usability test of the EAT performed in conditions very similar to the first study [@fritzReinventingWheelEmotional2015]. The aim is to conduct a sort of secondary data analysis [@westonRecommendationsIncreasingTransparency2019] or a small internal meta-analysis [@gohMiniMetaAnalysisYour2016] to assess whether the characteristics of the EAT have been harnessed in neither, either, or both situations. The data-driven analysis will also be the chance to explore what type of information can be retrieved when data is collected through the same toolbox, but coming from instances of the EAT deployed in very different situations.

### Empirical Objectives {#.unnumbered}

The empirical objectives are one again twofold. First, respond to the specific research questions stated in each study, which may be of interest to scholars investigating whether and how endowing computer-mediated learning environments can be beneficial to learners. And second, collect first-hand data and know-how that can be directly exploited to assess the features of the EAT and, if possible, incrementally improve the overall toolbox.

## Thesis Outline {.unnumbered}

The thesis is organized in four parts. Part I provide the overall theoretical background of the contribution. It starts from the general outlook of affective phenomena in learning and educational sciences and concludes with the specific inner mechanisms of emotion elicitation, differentiation, communication and regulation that may underlie the instrumentality of an emotional awareness tool in computer-mediated learning environments. One of the main aims of the first part is to sketch the intricate picture that emerges from the integration of articulated phenomena such as learning and affect in a multi- and inter-disciplinary field as education technology. Part I therefore aims at producing a reasonable overview on the subject at hand and justify to the best explanation the theoretical and methodological choices adopted for the proof of concept and the empirical parts of the thesis. More specifically, Chapter 1 proposes an overview of the inter-disciplinary convergence about the importance of implementing affective phenomena in learning as a means to improve both learning processes and outcomes, and of the different approaches through which this objective can be sustained. Chapter 2 discusses emotion awareness and emotion awareness tools in computer-mediated learning environments, proposing fundamental assumptions about the reasons why emotional awareness may be of use. The chapter also proposes an abstract model of emotional awareness, which put into perspective some of the numerous intervening factors that may determine whether and how learners take advantage from an EAT. The abstract model will be used as a reference throughout the thesis. Chapter 3 focuses on emotion theories and appraisal theories more specifically, under the assumption that an EAT may best serve its purpose if it implements an emotion structure, from which learners can take advantage in terms of emotion meaning-making and strategic signaling. The chapter will provide a definition of emotion that will inform the computational model at the core of the EAT.

Part II presents the implementation of the EAT and the toolbox built around it as a proof of concept, that is, a functioning device for which conceptual features have been prioritized over more fundamental practices in software development. Chapter 4 resumes previous work in the design of a prototype, named Dynamic Emotion Wheel, which will be extended both theoretically and technically in order to fulfill the multipurpose perspective. Chapter 5 illustrates the inner functioning of the parsimonious computational model that links appraisals criteria to the conscious emotional experience adopting a *k-nearest neighbor* approach, which can be scaled to multi-dimensional underlying affective spaces. Finally, Chapter 6 briefly outlines how a user-friendly toolbox has been built around this core model for scholars and practitioners to adapt the tool to their needs, as well as the features of the toolbox fostering comparability of studies and sharing of material and data. It is important to mention, though, that the proof of concept is presented before the empirical contribution for easing the general exposition of the thesis. As mentioned above, though, following an interaction design and user-centered process, Part II and Part III are highly intertwined: the technical and methodological implementation of the proof of concept has both informed and been informed by the empirical contributions. This means that Part II presents a *minimum viable product*, which is the result of the last iterative process, based on data and expertise gathered through the empirical contributions. At the same time, some of the technical and methodological elements resulting from the last iteration were not available for the empirical contributions. As a consequence, empirical contributions do not necessarily take full advantage or explore thoroughly all the available features. Furthermore, to keep this part of the contribution to a manageable length and accessible to non-technical readers, features of the device lacking a clear scientific impact will not be illustrated thoroughly. Interested readers may refer to the Code and Data section at the end of this Introduction for further details.

Part III comprises the three empirical contributions. Chapter 8 illustrates the experiment where the interface of the EAT is manipulated to create three different *flows* of emotional awareness. The experiment is characterized by a controlled environment, where participants were exposed to exactly the same stimuli through the simulation of a collaborative problem-solving task. The use of an eye-tracking device is also adopted to measure how participants interact with the different elements on screen when an EAT is integrated alongside a computer-mediated collaborative task. Chapter 9 reports the longitudinal study, which is performed in two different classes following a Master in education technology at Geneva University. The chapter introduces the Emotion Awareness Usefulness (EAU) scale, a tentative scale to measure emotional awareness instrumentality based on theoretical ground. An attempt is also made to investigate whether emotional competence, measured from a performance-based perspective, may be determined as an intervening factor in the use and perception of the EAT. Finally, Chapter 10 illustrates the data-driven analysis of the comprehensive assessment of the EAT. Different analysis will be carried out to assess the main features of the EAT, namely the presence of appraisal dimensions to evaluate the situation, as well as the use of an underlying affective space that informs the computational model in order to suggest the most likely subjective feeling to occur.

Part IV concludes the thesis with the general discussion of Chapter 11 and the Conclusion. The Appendices at the end of the manuscript only provide links to supplemental material which are available online.

## Code and Data {.unnumbered}

The code and data for the toolbox as well as for the computational manuscript of the thesis -- including thus data of the empirical contribution -- are publicly available. Since the code span different repositories, but that those repositories may change the underlying technology or location over time, the different links are grouped in a single web page. The page is hosted on the TECFA server, active since the early 1990's, which has a long tradition of keeping URL stable over time. I hope this tradition will go on.

<https://tecfa.unige.ch/perso/mafritz/thesis/code-and-data/>
