# Theoretical Convergence About the Instrumentality of Emotional Awareness in Distance Learning Settings

```{r theoretical-background-setup, include=FALSE, echo=FALSE}
library(tidyverse)
library(papaja)
library(here)
library(knitr)
library(kableExtra)

```

This chapter provides an overview of the extant literature, combining different sources of scientific knowledge, which corroborate the interest for endowing distance learning settings with emotional awareness. The overall perspective adopted in the chapter is therefore rather inductive, with a collection of theories and empirical evidence that support the pertinence of emotional awareness. A *bona fide*, uncritical approach to the extant literature is warranted by two intertwined reasons. First, there is consensus among different scholars about the fact that the scientific study of emotion in learning -- and distance learning more specifically -- is a recent line of inquiry [@pekrunInternationalHandbookEmotions2014; @pekrunProgressOpenProblems2005; @cerneaSurveyTechnologiesRise2015; @arguedasOntologyEmotionAwareness2015; @bakerAffectiveLearningTogether2013; @graesserEmotionsAdvancedLearning2014; @eligioEmotionUnderstandingPerformance2012; @molinariEmotionFeedbackComputermediated2013; @lavoueEmotionAwarenessTools2020; @brackettPermissionFeelUnlocking2019; @reisAffectiveStatesComputersupported2018]. At such an early stage, a *loosening*, rather than a *tightening* approach can therefore help cross-fertilization and discover elements of interest [@fiedlerCycleTheoryFormation2004]^[This is limited, though, to the scientific inquiry, whereas in an applied context, caution should be taken not to *play with people's feelings*]. Second, considering the dependency of emotional awareness from technology in the context of distance learning, it remains to be determined whether emotional awareness can lead to theory formation, in the sense of a causal network of risky predictions about phenomena of interest, or it has *only* the potential to intervene as a technological support, regardless of its  explanatory power [@meehlAppraisingAmendingTheories1990]. In other words, if it were to be found that endowing distance learning with emotional awareness results in beneficial effects for learners, it may be *deployed* as-if, waiting for theoretical explanations to *tighten* its causal effects at a later stage [@fiedlerCycleTheoryFormation2004; @meehlAppraisingAmendingTheories1990; @scheelWhyHypothesisTesters2020]. 

The chapters starts with an organized, but essential, overview of current trends in learning psychology and education sciences, which consider the interplay between affect and learning as a crucial interaction to foster learning processes and outcomes. Second, it illustrates how the rationale behind the instrumentality of emotional awareness in distance learning settings emerges from the convergence of multiple disciplines and perspectives, comprising -- but not limited to -- psychological theories about the pivotal role affect plays at the intra- and inter-personal levels; trends in computer-mediated communication and collaboration to implement awareness tools in technology enhanced environments; and current perspectives in the field of affective computing, which aims at empowering learning environments with affect- and emotion-aware systems. The last part of the chapter points out some methodological challenges in the scientific inquiry of emotional awareness. One of these challenges, specifically, relates to differences in the interpretation and use of the concept *emotion*, which is a topic discussed at length in the next chapter. Until a formal definition of *emotion*, thus, the more general term *affect* is often adopted in the narrative structure of the text, whereas -- as stated in the introduction -- an effort will be made to maintain authors' use of the term adopted in their work.

## Affect and Learning

The interplay between affect and learning is being investigated at various level of granularity, from the micro-level of neuroscience [*e.g.*, @immordino-yangEmotionsLearningBrain2016] to the macro-level of how education curricula and institution should reform their programs in order to take affective experiences into account [*e.g.*, @brackettPermissionFeelUnlocking2019]. Rather than a layered analysis, though, this section proposes a selection of contributions -- privileging research related to learning with technology whenever possible -- organized in three non-mutually exclusive and highly intertwined categories: (1) research that focuses *primarily* on the effects of learning processes and outcomes on affect; (2) research that focuses *primarily* on the effects of affect on learning processes and outcomes; and (3) research that focuses *primarily* on how either or both directional effects can be mediated or moderated by various forms of socio-affective competences such as emotional intelligence, intrinsic or extrinsic emotion regulation, and the like. This division is adopted mainly for easing the illustration of various contributions and is not fundamental for the remainder of the manuscript. The main aim of the section is to depict an overall and growing cross-disciplinary and inter-disciplinary interest in considering learning as the results of cognitive, social, and affective interactions, and how emotional awareness through the use of an EAT relates to these research areas.

### The Effects of Learning on Affect

Research investigating the effect of learning on affective phenomena is primarily concerned in determining what affective reactions are elicited by learning processes and situations, and what are the reasons and mechanisms that concur in eliciting such reactions. According to Pekrun [-@pekrunControlValueTheoryAchievement2006; -@pekrunProgressOpenProblems2005], for instance, the scientific study of emotion in education emerged in the last few decades by extension of previous work that was primarily focused on reducing anxiety during test exams. In an effort to broaden the perspective on the interplay between emotion and learning, Pekrun set forth an overarching theory, named the *Control-Value Theory of Achievement Emotions* [@pekrunControlValueTheoryAchievement2006], which accounts for eliciting mechanisms and consequences of learning situations where some form of achievement is at stake (*e.g.*, passing an exam). The theory states that learners evaluate their learning experience according to two criteria: the subjective control that learners feel over the learning process, and the intrinsic value that they confer to the achievement outcome. Different emotions, such as *frustration*, *enjoyment*, or *boredom*, are then elicited based on the specific evaluation that learners make about the situation, combined with the temporal dimension of the evaluation, that is, whether it is retrospective, perspective, or ongoing. The Control-Value theory is depicted more thoroughly in the next chapter, but is presented here as a line of inquiry that aims at explaining how and why certain emotions are elicited by learning processes. In this regard, it is also worth mentioning that achievement emotions are only one possible *kind* of emotion that may be elicited in learning. Pekrun and Linnenbrink-Garcia [-@pekrunIntroductionEmotionsEducation2014] proposes a taxonomy articulated around four *families* of emotions related to learning and educational settings:

1. *Achievement emotions*, already mentioned, elicited by activities or outcomes that refer to standards of evaluation. Examples of achievement emotions are *pride* or *shame* that may occur depending on the result of an exam. 
2. *Epistemic emotions*, elicited by processes that learners enact to assimilate and accommodate new information in the intent to build knowledge. Examples of epistemic emotions are *curiosity* or *surprise* emerging from incoming information that may contrdict extant knowledge;
3. *Topic emotions*, elicited directly by the content of the learning activity, independently of achievement or epistemic processes. Examples of topic emotions are *empathy* towards the fate of a character in a novel, or strong affective reactions that may arise from historical or political events;
4. *Social emotions*, elicited by inter-personal dynamics that are pervasive in learning and educational contexts, such as the relationship with colleagues or teachers. Examples of social emotions are *admiration* for a colleague, who was of help in solving a problem, or *anger* towards a free-rider in a group assignment. 

One important element to retain from this taxonomy is that the same *discrete* emotion may pertain to different *families* according to what is the object focus of the eliciting situation [@pekrunControlValueTheoryAchievement2006; @pekrunIntroductionEmotionsEducation2014]. For instance, *frustration* may be triggered by the result of an exam (achievement), by the self-oriented perception of inability to understand information (epistemic), by the unwillingness to manipulate scientific equipment in a science class (topic), or by the difficulty in explaining to others one's opinion (social).

Another research approch pertaining to the effects of learning on affective phenomena consists in focusing on the kind and frequency of specific affective phenomena emerging from learning experiences, which is in itself valuable knowledge both for instructional designers and researchers, without necessarily proposing an eliciting mechanism. Of particular interest to the present thesis, for instance, is a recent selective meta-analysis conducted by D'Mello [-@dmelloSelectiveMetaanalysisRelative2013] on affective states experienced during individual learning with technology. Combining 24 studies from 5 different countries and from different level of formal education (from middle school to adult students), D'Mello (*ibid.*) computed the relative frequency of different affective states recorded from different sources, from self-report to retrospective video analysis from trained judges. Results show that only one affective state, defined as *engagement/flow*, was consistently frequent in most of the studies. More *traditional* affective reactions such as *anger*, *anxiety*, *boredom*, *fear*, *frustration*, *happiness*, *sadness* and *surprise* were either infrequent, or subject to great heterogeneity between studies.

Reis and colleagues [-@reisAffectiveStatesComputersupported2018] performed a similar meta-analysis, but encompassing affective states during Computer-Supported Collaborative Learning (CSCL) [@dillenbourgEvolutionResearchComputersupported2009; @stahlComputersupportedCollaborativeLearning2006; @suthersTechnologyAffordancesIntersubjective2006], integrating thus also a collective, human-to-human interaction perspective. Starting from an initial corpus of over one thousand contributions between published articles and conference papers, the authors extracted 58 papers that met all the criteria they set forth. From this restricted corpus of articles, the authors computed the number of papers citing different discrete affective states, belonging to different categories of affective phenomena (personality traits, emotions, moods, and socio-emotional factors). With respect to affective states identified as emotion, the authors tallied 29 discrete emotions that appeared in a minimum of two and a maximum of eight papers. The most frequently cited discrete emotions appearing 4 times or more are: *angry*, *confused*, *disgust*, *pride*, and *tired* (in four papers); *curious*, *excited*, *interested*, *joy*, *sadness* and *surprise* (in five papers); *anxious*, *bored*, *relaxed* and *anger* (in six papers); *fear* (in seven papers); and *frustration* (in eight papers). The work of Reis and colleagues (*ibid*) was not limited to the frequency of affective states, but encompassed a broader perspective on the past and future of the study of affective phenomena in CSCL and will therefore be cited in other parts of this chapter.

This brief selection of contributions corroborates the fact that learning does indeed elicit affective phenomena, but that those phenomena varies greatly depending on a number of situated factors. Research is therefore implicated in determining the mechanisms of elicitation, as well as explaining the determinants of the variance in affective experiences according to different learning contexts, such as individual vs. collaborative. In this regard, an EAT may contribute to shed light on eliciting factors, by providing for instance useful information about when an emotion occur, and it can also be integrated in different learning situations to account for differences in the kind and frequency of experienced emotions.

### The Effects of Affect on Learning

Another line of inquiry, which is highly intertwined with the one illustrated in the previous subsection, aims at investigating whether affect in general, and specific affective states more specifically, have effects on learning, for instance by fostering or hindering learning processes or outcomes. Research in this area may vary greatly depending on the level of analysis and the affective phenomena they target. 

With respect to the level of analysis, it may concern the interplay between affective and cognitive processes such as attention, perception, memory and decision making, which are all evidently implicated in learning processes and outcomes [@broschImpactEmotionPerception2013; @immordino-yangEmotionsLearningBrain2016; @pessoaCognitiveemotionalBrainInteractions2013]. Research may target more complex and compounded information processing phenomena, such as creativity or problem-solving [@avryAchievementAppraisalsEmotions2020; @avrySharingEmotionsContributes2020; @davisUnderstandingRelationshipMood2009]. But also more inter-personally oriented processes, in which affective phenomena may regulate or undermine collaborative situations [@andriessenSociocognitiveTensionCollaborative2011; @jarvenojaRegulationEmotionsSocially2013; @bakerAffectiveLearningTogether2013].

Concerning the kind and nature of affective phenomena, research may dichotomize them in *positive* and *negative* [@pekrunPositiveEmotionsEducation2002; @hascherLearningEmotionPerspectives2010; @harleyDevelopingEmotionAwareAdvanced2017], using sometimes implicit criteria of categorization based on a simplified form of *valence* (pleasant vs. unpleasant, but see @colombettiAppraisingValence2009 or @shumanLevelsValence2013 for an overview of how valence can be much more complex). In other cases, the effect of discrete affective states is targeted more specifically by inducing a specific affective state through manipulation, and then measure its effects on learning processes or outcome [@hascherLearningEmotionPerspectives2010; @schwarz2003mood]. For instance, D'Mello and colleagues [@dmelloConfusionCanBe2014] induced confusion in participants by providing, through a virtual agent in a learning environment, contradictory and incorrect information about the topic at hand. The authors found empirical evidence suggesting that even a -- *soi-disant* -- *negative* emotion such as *confusion*, if appropriately induced, regulated and resolved, can be beneficial to learning. 

The overall picture that emerges is necessarily scattered and sometimes contradicting. Affect and learning are two extremely complex phenomena and the combination of the two leads, exponentially, to further complexity. Considering a simple correlation between *positive* emotion and *positive* learning outcomes, and conversely between *negative* emotion and *negative* learning outcomes, is therefore diminishing of both learning and affect [@hascherLearningEmotionPerspectives2010; @pekrunInternationalHandbookEmotions2014; @shumanConceptsStructuresEmotions2014]. As summarized by Pekrun and Perry [-@pekrunControlValueTheoryAchievement2014, p. 134] "with few exceptions, any emotion can prove to be either adaptive or maladaptive". A similar view is taken by Hascher [-@hascherLearningEmotionPerspectives2010]:

>It is too simple to suppose that negative emotions have negative effects on learning, and positive
emotions have positive effects. What arguments can be found to clarify
a statement like ‘Happiness during learning is negative for the learning process’? The question of
negative effects of positive emotions (and of positive effects of negative emotions) is very
interesting, because it goes beyond plausibility arguments. 
--- @hascherLearningEmotionPerspectives2010, p. 15

In this regard, an EAT takes in somehow an agnostic position, since it may register and convey all sort of affective phenomena that are considered potentially relevant to the learning context in which it is deployed, regardless of whether they are supposed to hinder or foster learning processes and outcomes. At the same time, though, the EAT should build emotional meaning making and awareness on the ground of affective phenomena that are known to play a prominent role in learning processes and outcomes, because that would maximize the instrumentality both of the tool in itself, and the information it conveys.

### Socio-Affective Competences in Learning

Finally, a third approach in research about affect and learning focuses on empowering learners with skills, allowing them to deal with the social and emotional challenges that they face during various phases of the learning process. Oftentimes, the scope of this line of research goes beyond learning and educational settings, and aims at preparing learners -- especially in early educational programs -- to take advantage of their social and emotional skills in life more generally.

Research of this third kind often -- but not always -- refers to the concept of Social and Emotional Learning (SEL), which has a long tradition in education [see @osherAdvancingSciencePractice2016 for a recent overview], and for which Brackett and colleagues [-@brackettRULERTheoryDrivenSystemic2019] provide a recent definition:

>Today, SEL refers to the process of integrating cognition, emotion, and behavior into teaching and learning such that adults and children build self- and social awareness skills, learn to manage
their own and others’ emotions and behavior, make responsible decisions, and build positive relationships. --- [@brackettRULERTheoryDrivenSystemic2019, p. 144] 

One extensive approach to this form of social and emotional learning is represented by the RULER approach [@brackettEnhancingAcademicPerformance2012; @brackettRULERTheoryDrivenSystemic2019; @hoffmannTeachingEmotionRegulation2020; @nathansonCreatingEmotionallyIntelligent2016], an acronym that stands for Recognizing emotions in oneself and others; Understanding the causes and consequences of emotions; Labeling emotions with a nuanced vocabulary; Expressing emotions in accordance with cultural norms and social context; and Regulating emotions with helpful strategies. The RULER approach relates to various psychological theories, among which the concept of emotional intelligence as originally posited by Salovey and Mayer [-@saloveyEmotionalIntelligence1990] and more recently updated in light of further development [@mayerAbilityModelEmotional2016]. According to the authors, emotional intelligence is an ability comprising four branches: (a) perceive emotions accurately, (b) use emotions to accurately facilitate thought, (c) understand emotions and emotional meanings, and (d) manage emotions in themselves and others. 

Other models and conceptualization of emotional intelligence have emerged in the last few decades, which have sometimes increased the hype over the concept (*e.g.*, its primary over *traditional* intelligence), but also contributed to a better assessment of its fundamental nature and relation with other form of intelligence [@ashkanasyReintroducingEmotionalIntelligence2015; @chernissEmotionalIntelligenceClarification2010; @maccannCopingMediatesRelationship2011; @mestreModelsCognitiveAbility2016; @petridesDevelopmentsTraitEmotional2016; @schererComponentialEmotionTheory2007; @schlegelGenevaEmotionalCompetence2018; @murphyIntelligenceInterpersonalSensitivity2011; @lockeWhyEmotionalIntelligence2005; @ashkanasyReintroducingEmotionalIntelligence2015]. There is nowadays a growing consensus, for instance, in considering emotional intelligence -- or related formulations -- as either a relative stable trait [*e.g.*, @petridesRoleTraitEmotional2004], or an ability or competence that can be trained [*e.g.*, @mayerAbilityModelEmotional2016; @schererComponentialEmotionTheory2007] and also measured from a performance standpoint [@schlegelGenevaEmotionalCompetence2018].

Another subject of inquiry bridging learning and affect relates to various forms of regulatory processes, which are considered as fundamental to learning processes both at the individual and collective levels. A consistent body of research, for instance, refers to three types of regulatory processes: (1) self-regulated learning, (2) co-regulated learning, and (3) socially-shared regulation of learning [@jarvelaEnhancingSociallyShared2015; @jarvelaSociallySharedRegulation2016; @millerScriptingAwarenessTools2015; @winneWhatStateArt2015]. According to Miller and Hadwin [-@millerScriptingAwarenessTools2015, p. 574], who proposed a recent overview from different sources, regulation of learning "can be defined as an intentional, goal directed metacognitive activity in which learners and groups take strategic control of their actions (behaviour), thinking (cognitive), and beliefs (motivation, and emotions) in the context of dynamic social interactions". In self-regulated learning, the person intentionally acts upon her own internal states that may have effect on her learning process. In co-regulated learning, learners engage in mutual, but still individually-oriented, regulation of internal states, in an effort to improve the collaborative task. Finally, in socially-shared regulation, which emerges from the coordination of self- and co-regulated learning, the group as a whole becomes the target of the regulatory processes in a synchronized and productive manner (*ibid*). 

This third line of inquiry, thus, consider affect in the light of integrated processes, which require both effort and *some* form of competence for them to be instrumental to learning. This perspective resonates with the voluntary use of an EAT, which requires effort and inferential processes, but also with the possibility that the use of the EAT may contribute to better regulate socio-affective dynamics.

### Synthesis

This first section of the chapter presented a brief overview of three complementary research areas linking affect and learning. The implementation of an EAT relates to all three areas since it presupposes (1) that learning elicits affective phenomena, so that learners have affect-related information upon which they can reflect and that they can convey; (2) that affective phenomena experienced during learning have an impact on learning processes and outcomes depending on the specifics of the situation at hand, rather then on a predefined list of discrete affective states that always foster or hinder learning ; and (3) that for taking full advantage of the affect-related information, both at the intra- and inter-personal levels, some effort and ability in extrapolating meaning from emotional information is necessary.

Once established the pertinence of an EAT with respect to current areas of research on the interplay between affect and learning, the next step is to provide information about the mechanisms that an EAT may sustain and which can be beneficial to learning processes and outcomes. The next sections of the chapter will gather information broadly from three sources: psychological mechanisms in emotional awareness; awareness tools in computer-mediated communication and collaboration; and affective computing applied to technology enhanced learning environments.

## Affect-Aware Systems in Computer Mediated Learning Environments

The pivotal role attributed to affective phenomena in learning and education at large has recently pushed several scholars to investigate modalities for, and benefits in endowing computer-mediated learning environments with systems that integrate affective phenomena [@arguedasOntologyEmotionAwareness2015; @calvoFeelingThinkingComputing2015; @calvoFrontiersAffectAwareLearning2012; @feidakisReviewEmotionAwareSystems2016; @grawemeyerAffectiveLearningImproving2017; @harleyDevelopingEmotionAwareAdvanced2017; @cerneaSurveyTechnologiesRise2015; @calvoAffectDetectionInterdisciplinary2010]. These systems, which are often referred to as affect-aware or emotion-aware systems (*ibid.*), may vary greatly in their complexity, scope, ways to measure affective phenomena, use of the affective information, and so on. For instance, affective systems can be oriented -- exclusively, primarily or equally -- towards the learner's individual affective states, the collective affective states of a group sharing common learning processes and outcomes, the affective states of teachers, or even the affective states of computerized agents implemented into the system, such as embodied tutors [@cerneaGroupAffectiveTone2014; @craigEmoteAloudLearning2008; @lavoueEmotionAwarenessTools2020; @leeTeachersEmotionsEmotion2016; @mantySocioemotionalInteractionCollaborative2020; @naykkiSocioemotionalConflictCollaborative2014]. 

Even though affective systems are mainly driven by autonomic affect detection [@calvoAffectDetectionInterdisciplinary2010] and often aim at providing the learning environment with some form of *adaptive intelligence*, such as affective feedbacks,  that reacts to or acts upon learners affective states [@dmelloFeelingThinkingComputing2015; @harleyDevelopingEmotionAwareAdvanced2017], recent and overarching contributions have attempted to put affective systems in computer-mediated learning environments into broader perspectives [@calvoFrontiersAffectAwareLearning2012; @cerneaSurveyTechnologiesRise2015; @dmelloFeelingThinkingComputing2015; @feidakisReviewEmotionAwareSystems2016; @harleyDevelopingEmotionAwareAdvanced2017]. It is therefore worth to take advantage of the extant literature to seek for commonalities and differences with respect to an EAT with the characteristics stated in the introduction.

### Affective Systems and Affective Computing

Affective systems can be broadly categorized according to the objectives of affective computing, a recent interdisciplinary field investigating "computing that relates to, arises from, or deliberately influences emotions" [@picardAffectiveComputing2000, p. 3]. Picard [-@picardAffectiveComputing2009] identifies four, non mutually exclusive, research areas in affective computing: (1) technologies for sensing, recognizing, modeling, and predicting emotional and affective states;
(2) methods for computers to respond intelligently and respectfully to handle perceived affective information; (3) technology for displaying emotional information or mediating the expression or communication of emotion;  and (4) computational mechanisms that stimulate internal emotions or implement their regulatory and biasing functions. 

Affective systems in computer-mediated learning environments more often relate to the first two categories identified by Picard [@calvoFrontiersAffectAwareLearning2012; @dmelloFeelingThinkingComputing2015; @feidakisReviewEmotionAwareSystems2016; @harleyDevelopingEmotionAwareAdvanced2017]. For instance, in their glossary to an overarching chapter on the integration of affect in advanced learning technologies, D'Mello and Graesser [@dmelloFeelingThinkingComputing2015, p. 2] define an affect-aware learning technology as "an intelligent technology that considers a learner's affective and cognitive states in its pedagogical decision making". The authors (*ibid.*) identify two ways in which affect-aware learning technologies manifest their *intelligence*: (1) by proactively inducing or impeding particular affective states, which are considered as either fostering or hindering learning; and (2) by reacting to specific affective states as they arise, for instance in an attempt to remedy to affective states that may undermine the overall learning experience (see above the general discussion of interplay between learning and affect). More recently, Harley and colleagues [@harleyDevelopingEmotionAwareAdvanced2017] have extended the dichotomy proposed by D'Mello and Graesser (*ibid*) and adopted it in an effort to provide a theoretically-guided taxonomy for the development of emotion-aware learning technologies. The contribution adopts Pekrun's Control-Value theory of achievement emotions [@pekrunControlValueTheoryAchievement2006], already introduced above, as the guiding framework for the taxonomy, corroborating the importance to bridge techno-centric and theoretical approaches.

### An Interactional Approach to Affect^[This section builds on, but extends with more recent contributions, a a similar section in Fritz (2015)]

At first blush, the third research area of affective computing identified by Picard [-@picardAffectiveComputing2009] stands out as the best match for an EAT: technology for displaying emotional information or mediating the expression or communication of emotion. The description perfectly fits its purpose, which resonates with all the features proposed by the description: it aims at displaying emotional information, *and* mediate the expression *and* communication of emotion. According to Boehner and colleagues [-@boehnerHowEmotionMade2007], though, this particular line of research has been neglected in affective computing, whose mainstream approach considers emotion as an internal and individual phenomenon. They identify this mainstream approach to emotion as *informational*, which they qualify as "rooted in a longer laboratory-science tradition of studying emotion in which subjective experience is considered suspect, to be replaced by objective measures" [@boehnerHowEmotionMade2007, p. 276]. The authors advocate instead an *interactional* approach, which (1) focus on how computers can help users understand their emotions, rather than how computers can understand users’ emotions; and (2) sees emotions as a cultural, dynamic and social phenomena, constructed in action and interaction. The position taken by Boehener and colleagues (*ibid.*) is stated very clearly in this passage, that is worth citing at length, for it targets perfectly the main aim of an EAT:

> The role of affective systems is not to transmit pre-existing emotional units, but to provide a resource for emotional meaning-making. Success of such a system is measured by whether users find the system’s responses useful for interpreting, reflecting on, and experiencing their emotions. Evaluation does not aim at finding a user’s original, "true" emotions, but in tracking
how emotions are constructed and interpreted over time, and correlating these dynamics with
aspects of system design. --- @boehnerHowEmotionMade2007, p. 287

In support of this claim, the article (*ibid.*) illustrate and compare different affective systems that have either an *informational* or *interactional* approach. For instance, one *interactional* system pertained precisely to the notion of emotional awareness. Co-workers in a shared space were asked to fill a survey about their emotions in real-time and, according to their responses, an abstract painting projected on a wall changed background color, the number and cluster of dots, and the speed of movement in the animation as a function of aggregates and averages of the survey responses. The authors report that co-workers were puzzled by the abstract representation, which contributed in fostering the co-construction of emotional meaning-making advocated in the *interactional* approach.

More recently, Cernea and Kerren [-@cerneaSurveyTechnologiesRise2015], inspired by the work of Boehener and colleagues (*ibid*.), proposed a categorization of technologies *on the rise* for emotion-enhanced interaction. The authors main objective "was to focus on technologies that satisfy two main requirements: having been used increasingly often in affect detection for interaction purposes, and having a proven track of *portability*, *non-intrusiveness* and *low cost*" [@cerneaSurveyTechnologiesRise2015, p. 72]. Even though the authors target more complex affective system -- often using multi-modal sensory information, such as tracking and recognizing facial expressions, eye-movements or pupil dilation, or brain-computer-interfaces -- the categorization they propose is relevant also to a *simpler* system. The authors identify three types of affective systems from an interactional stand-point, proposed here in an condensed form (*ibid.*, p. 78):

1. *Affective-awareness systems*, designed to improve affective self-awareness of a user (i.e., internal affective awareness) *or* awareness of the emotions of other users (i.e., external affective awareness) in collaborative or competitive environments, for instance.
2. *Emotion-adaptive systems*: which adapt interaction based on the use affective state *or* mimic affective states with the purpose of enhancing the user experience and efficiency.
3. *Emotion modeling systems*, wich do not simply adapt to user affective states, but try to influence these states as well.

An EAT belongs clearly to the first category of *affective-awareness systems*. The presence of this category corroborates the fact that emotional awareness is considered crucial also from an affective computing perspective. 

### Emotion-Aware Systems in E-Learning

Examples of contribution from an *affective-awareness systems* perspective mainly driven by affective computing is provided by Feidakis and colleagues [@feidakisEndowingElearningSystems2011; @feidakisProvidingEmotionAwareness2014; @feidakisReviewEmotionAwareSystems2016], who investigated emotion-aware systems in computer-mediated environments, both from theoretical and empirical perspectives, highlighting though that the topic has received so far limited attention. Their work is also primarily concerned with intelligent learning environments, but some of their contribution have more similarities with the use of an EAT as posited in the present thesis. 

For instance, the authors draw extensively from emotion theories [@feidakisReviewEmotionAwareSystems2016; @feidakisProvidingEmotionAwareness2014]. Furthermore, in an overarching review of emotion-aware systems for e-learning, Feidakis and colleagues [-@feidakisReviewEmotionAwareSystems2016, p. 217] define emotion awareness as "the *implicit* or *explicit collection of emotion data* and the *recognition* of *emotion patterns*" (italics in the text). They therefore draw a distinction between data derived from autonomic affect detection (implicit), and data provided through first-person subjective report of feelings (explicit). Feidakis and colleagues' work is also relevant to the present contribution because they advocate the adoption of emotion-aware systems also into *simpler* learning management systems, whereas affective systems are often deployed in more technology-intensive setings, such as virtual environments or educational games.

### Affective Feedback

Affective systems often -- but not always -- complement affective detection with what are commonly referred to as *affective feedbacks* [@arguedasOntologyEmotionAwareness2015; @feidakisProvidingEmotionAwareness2014; @grawemeyerAffectiveLearningImproving2017; @robisonEvaluatingConsequencesAffective2009], which are often distinguished from more traditional *cognitive feedbacks* [@nelsonNatureFeedbackHow2009]. As the field more generally, affective feedbacks in affective systems are a recent line of inquire and the extant literature is therefore very cautious about their deployment and efficacy, as well as the very nature of what represents an affective feedback (*ibid*.). Broadly speaking, an affective feedback is a reaction of the system that explicitly targets the affective phenomena detected and attempts to instrumentally act upon it to improve learners' situation, either from an affective (*e.g.*, *empathetic*) or task-oriented point of view [@robisonEvaluatingConsequencesAffective2009]. 

Affective feedback is tightly related to a form of *intelligence* in affective systems, which computes appropriate treatment and useful output, and is therefore outside the scope of a simpler system. They nevertheless call for attention in evaluating whether emotional expression can be effective on itself, or it should be coupled with some form of feedback from the system.

### Self-Report From An Affective Computing Perspective

A last element of interest that can be derived from the extant literature driven mainly by an affective computing perspective concerns how self-report is assessed. Given that this field makes extensive use of autonomic identification of affective phenomena, it is of interest to seek for identified drawbacks in the use of a voluntary, self-report tool. Views from an affective computing perspective can therefore complement, with information derived from computer-mediated environment, more *traditional* assessment about validity and reliability of self-report in measuring affective phenomena [*.g.*, @maussMeasuresEmotionReview2009; @mortillaroEmotionsMethodsAssessment2015; @schererWhatAreEmotions2005].

In a recent and overarching contribution about measuring emotions in computer-mediated learning environments -- referred to as Computer-Based Learning Environments (CBLE) in the contribution -- Harley [@harleyMeasuringEmotionsSurvey2015] reviews four main methodologies: facial expression coding, body posture and physiological measurement devices, log file data, and self-report measures. The author confirms that self-report is a widely adopted method of measure even in CBLE, which can be administered before, during or after the learning activities. It has the advantage of being easy to administer, and collected data are generally also easy to analyze and compare, especially when the self-report consists of a set of discrete affective states. On the other hand, though, Harley (*ibid.*), points out that self-report is an *off-line* measure, since learners must divert their attention from the learning activity to the self-report measure. This diversion is particularly disrupting when the self-report is asked at frequent intervals, or is repetitive in its administration. These seem the main drawbacks that are specific, or at least of particular relevance, to CBLE. Other drawbacks identified in the contribution are in fact shared with general and known shortcomings in self-report measures more generally, and can be roughly divided in: (a) authenticity of reported experience; (b) unwillingness to disclose one's own affective experience for normative pressure or social desirability; (c) latency time between the felt affective phenomena and the report, which may introduce bias in recollection; and (d) the action of self-reporting may elicit corollary phenomenon that modifies the original affective state [@harleyMeasuringEmotionsSurvey2015; @maussMeasuresEmotionReview2009; @mortillaroEmotionsMethodsAssessment2015a; @schererWhatAreEmotions2005].

### Synthesis

This section provided an overview of affective systems implemented in computer-mediated learning environments from perspectives mainly driven by affective computing. The extant literature provides similarities between affective systems and an EAT as the one prospected in the thesis. First, there is a growing interest in affective computing for *interactional* affective technologies that provide users with the possibility to impinge on emotion meaning-making. Second, emotional awareness is an active research topic in affective computing, and in computer-mediated learning environments more specifically. Third, even though the field of affective computing was originally theory-agnostic and more focused on technical features in affect detection and processing [@calvoAffectDetectionInterdisciplinary2010], recent developments in the field corroborate a more tight relationship with theories, which can be beneficial in both direction: theory can inform affective systems, and affective systems can inform theory [@calvoAffectDetectionInterdisciplinary2010; @marsellaComputationalModelsEmotion2010; @schererBlueprintAffectiveComputing2010; @pekrunInternationalHandbookEmotions2014].

On the other hand, most affective systems make the assumption that specific affective phenomena can hinder or foster learning and, congruently, deploy proactive or reactive strategies to actively intervene in the process. As stated in the introduction, the kind of EAT targeted by the thesis attempts to maintain a certain degree of agnosticism towards the instrumentality of specific affective phenomena and bestow learners with the responsibility to integrate the emotional information at hand, for them to take advantage of it. In this sense, an EAT is therefore closer to an awareness tool than it is to an affective system. The next section thus proposes an overview of the extant literature on awareness tools.

## Awareness Tools in Computer-Mediated Learning Environments

Whereas affective systems in computer-mediated learning environments stem directly from affective computing, that is, from an affect-centered approach, awareness tools adopted in learning settings originated primarily from the fields of Computer-Mediated Communication [@baltesComputerMediatedCommunicationGroup2002; @lickliderComputerCommunicationDevice1968; @fjermestadAnalysisCommunicationMode2004] and Computer-Supported Collaborative (or Cooperative) Work [@dourishAwarenessCoordinationShared1992; @grossUsercenteredAwarenessComputersupported2005; @grudinComputerSupportedCooperativeWork1994]. The transition and integration of that heritage in learning settings span different disciplines and approaches, from the need to provide learners' in distance education with a social presence to limit learners' sense of isolation [@gunawardenaSocialPresencePredictor1997; @sungFiveFacetsSocial2012; @paquelinDistanceQuestionsProximites2011; @charlierApprendrePresenceDistance2006; and @tuRelationshipSocialPresence2002] to the interdisciplinary field of Computer-Supported Collaborative Learning [@dillenbourgEvolutionResearchComputersupported2009; @dillenbourgWhatYouMean1999; @stahlComputersupportedCollaborativeLearning2006; @suthersTechnologyAffordancesIntersubjective2006], in which learners' collaboration must be sustained and coordinated at various levels -- cognitive, social, and affective -- to be effective [@bakerAffectiveLearningTogether2013; @janssenGroupAwarenessTools2011; @jarvelaEnhancingSociallyShared2015; @kreijnsSocialAspectsCSCL2013; @winneWhatStateArt2015].

This section provides an overview of the extant literature related to the flexible notion of *awareness* in computer-mediated learning environments, where awareness is here intended broadly as information about oneself and/or others, which is instrumental to one's own activity [@buderGroupAwarenessTools2011; @dourishAwarenessCoordinationShared1992; @schmidtProblemAwareness2002]. The section mainly draws from literature referring to Computer-Supported Collaborative Learning (CSCL) [@dillenbourgEvolutionResearchComputersupported2009; @dillenbourgWhatYouMean1999; @stahlComputersupportedCollaborativeLearning2006; @suthersTechnologyAffordancesIntersubjective2006], because -- even though the field is not limited to distance learning, but encompasses the use of computational devices also in face-to-face interaction -- research has, from the very beginning in the 1990's, reckoned the crucial role of building a *shared-understanding* of the learning context [@dillenbourgEvolutionResearchComputersupported2009; @dillenbourgSymmetryPartnerModelling2016; @roschelleConstructionSharedKnowledge1995]. For instance, Suthers [@suthersTechnologyAffordancesIntersubjective2006, p. 332] posits that CSCL is characterized by "processes of intersubjective meaning making and how technological affordances mediate or support such processes". Technology affordances are defined by Norman [@normanDesignEverydayThings2013, p. 11] -- in an adaptation of Gibson original definition of affordance [@gibson2014ecological] for the field of human-computer interaction -- as the “relationship between the properties of an object and the capabilities of the agent that determine just how the object could possibly be used” [see also @pucilloFrameworkUserExperience2014; @rizzoOriginDesignIntentional2006; @turnerAffordanceContext2005]. Norman draws a subsequent distinction between affordances and signifiers (*ibid*):

>Affordances determine what actions are possible. Signifiers communicate where the action should take place. We need both. --- @normanDesignEverydayThings2013, p. 14

### Forms of Awareness: From Social Presence to Mutual Modeling

A crucial element to consider at first is that the broad concept of awareness is tightly related to issues that have been identified in the last few decades about the articulation between distance learning and the need for *social presence*, especially in higher-education [@bates2005technology; @garrisonFirstDecadeCommunity2010; @jacquinotApprivoiserDistanceSupprimer1993; @jezegouCreerPresenceDistance2010; @kreijnsIdentifyingPitfallsSocial2003; @rourkeAssessingSocialPresence2001; @tuRelationshipSocialPresence2002]. The definition of social presence and whether this presence is a necessary element for learning to happen is still source of lively debate [@jezegouCreerPresenceDistance2010; @lowenthalSearchBetterUnderstanding2017; @rourkeLearningCommunitiesInquiry2009]. For instance, Lowenthal and Snelson [-@lowenthalSearchBetterUnderstanding2017] recently collected definitions from the most cited articles on social presence and identified five categories in which different definitions could be divided into (*ibid*, see Table 1 in the original article, p. 144):

* Social presence as *being there*, for instance in the definition by Dunlap and Lowenthal (2009): "the degree of salience (i.e., quality or state of 'being there') between two communicators";
* Social presence as *being real*, for instance in the definition by Gunawardena and Zittle (1997): "the degree to which a person is perceived as 'real' in mediated communication";
* Social presence as *projecting*, for instance in the definition by Rourke and colleagues (1999): "the ability of learners to project themselves socially and affectively into a community of inquiry";
* Social presence as *connecting*, for instance in the definition by Tu (2002): "the degree of feeling, perception, and reaction of being connected on CMC [computer-mediated communication] to another intellectual entity";
* Social presence as *belonging*, for instance in the definition by Picciano (2002): "a student's sense of being in and belonging in a course and the ability to interact with other students and an instructor".

The debate about which category or specific definition better defines social presence is beyond the scope of the present contribution, for which rather than the differences, it is worth pointing out commonalities, especially in considering socio-affective phenomena. In this regard, the definition of Rourke and colleagues (1999) clearly cites affect as a necessary dimension for learners' to project themselves in the social *milieu*, in which learning happens. Vaughan and Garrison (2005), cited in @lowenthalSearchBetterUnderstanding2017, states it very similarly: "social presence refers to the potential of participants to project themselves socially and emotionally". A view shared by Swan and colleagues (2008), also cited in @lowenthalSearchBetterUnderstanding2017, for whom "social presence refers to the degree to which learners feel socially and emotionally connected with others in an online environment". In the works of Jézégou (*e.g.*, 2010), *socio-affective presence* is one of the three fundamental dimensions of social presence alongside *cognitive presence* and *pedagogical presence*. According to Jézégou (*ibid*):

>the socio-affective presence in e-learning allows to support the cognitive presence resulting from  learners' transactions  to solve a problematic situation. It is generated by social interactions that contribute to establishing the symmetry of the relationship and the friendliness between learners, thus creating a socio-affective climate that is favorable to transactions within a digital communication space. --- @jezegouCreerPresenceDistance2010, p. 267, our translation from French.

A complementary view on the importance of the symmetry between learners in a computer-mediated learning environment is also posited by current trends in the field of Computer-Supported Collaborative Learning (CSCL) [@dillenbourgEvolutionResearchComputersupported2009; @dillenbourgWhatYouMean1999; @stahlComputersupportedCollaborativeLearning2006; @suthersTechnologyAffordancesIntersubjective2006] -- even though CSCL is not limited to distance learning, but also investigates the use of computational devices in co-located conditions. The field has, from the very beginning in the early 1990's, acknowledged the pivotal role of instructional designs and tools, which foster learners to build and maintain a shared understanding of the task at hand [@dillenbourgSymmetryPartnerModelling2016; @roschelleConstructionSharedKnowledge1995; @suthersTechnologyAffordancesIntersubjective2006]. According to Dillenbourg and colleagues [-@dillenbourgSymmetryPartnerModelling2016], for instance, to achieve shared understanding, learners must engage themselves in two intertwined processes: (1) a learner has to build and maintain a holistic representation of the colleagues with whom she shares the learning activity; and (2) the very same colleagues must possess sufficient information to build and update a holistic representation of the learner herself. Dillenbourg and colleagues (*ibid*) define the former process as *partner modeling* -- that is "the process of inferring one's partner's mental states" (*ibid*, p. 230) -- and the latter as *mutual modeling*, that is, *bi-directional* partner-modeling, which may happen at various nested levels (*e.g.* Jane speculates that Paul is aware of the fact that she expects him to be more involved in the argumentation).

It is posited, in fact, that the effort learners put into building a symmetrical representation of the partners in a collaborative task is a pivotal determinant of learning processes and, by extension, outcomes [@dillenbourgSymmetryPartnerModelling2016; @molinariKnowledgeInterdependencePartner2009; @sanginFacilitatingPeerKnowledge2011]. In this regard, it is useful to point out some important elements. First, symmetry does not mean that all the implicated learners must do, think, know, or feel the same thing. On the contrary, collaborative efforts are inherently characterized by fluctuations between socio-cognitive tensions and relaxations, which are instrumental to the learning process [@andriessenSociocognitiveTensionCollaborative2011; @jarvelaSociallySharedRegulation2016; @winneWhatStateArt2015]. Second, it is worth noting that, unlike other similar concepts implicating interpersonal accuracy [see @hallSocialPsychologyPerceiving2018 for a recent and integrative overview], mutual-modeling does not have to be persistently and precisely accurate, because that would require an effort that may take resources away from the learning activity [@dillenbourgSymmetryPartnerModelling2016]. Mutual-modeling is therefore particularly important at times when there are events of major concern for learners, who may benefit from cues about the suitability of persisting with or changing their behavior -- a process that, as it will be discussed in the next chapter more specifically, incidentally shares many commonalities with eliciting events in emotions [@schererWhatAreEmotions2005]. Finally, even though mutual-modeling is mainly driven  from a communicative point of view [@clarkGroundingCommunication1991], it also encompasses a broader variety of sources of information, such as what a person does, thinks, wants, or -- precisely -- feels [@bodemerGroupAwarenessCSCL2011; @dillenbourgSymmetryPartnerModelling2016; @engelmannKnowledgeAwarenessCSCL2009; @kirschnerAwarenessCognitiveSocial2015; @sanginFacilitatingPeerKnowledge2011; @eligioEmotionUnderstandingPerformance2012].

There is thus a growing consensus in considering affective phenomena instrumental to complementary *forms of awareness* in computer-mediated learning environments. The next subsection illustrates two broad ways in which awareness can be provided through technological artifacts in distance learning settings.

### How to Build and Convey Awareness: Scripting Tools vs. Group Awareness Tools

Awareness in a computer-mediated environment can be conveyed through different techniques or tools, from a green circle beside the *nickname*, which highlights that a person is online, to a fully fledged, three-dimensional *avatar* in virtual reality that can interact with all sorts of element in the environment, other *avatars* included. Rather than a technological overview of different means to provide awareness, this subsection focus on pedagogical strategies, which aims at leveraging on awareness to sustain learning in computer-mediated environments. In this regard, a useful categorization of tools is provided by Miller and Hadwin [-@millerScriptingAwarenessTools2015], who identify two -- non-mutually exclusive -- types of tools through which awareness is enacted to support self-regulation, co-regulation, or socially shared regulation of learning (see above): *scripting tools* and *group awareness tools*.

Scripting tools [*e.g.*, @dillenbourgOverscriptingCSCLRisks2002; @fischerScriptTheoryGuidance2013; @norooziFacilitatingLearningMultidisciplinary2012] are mainly adopted by teachers and instructional designer to scaffold the learning process, so that the awareness becomes an integral part in the learning activity. In other words, learning is organized as a sequence of steps, where some or all of these steps foster or require the emergence of awareness from an inter-subjective standpoint. A simple example of this process are the many cases of Massive Open Online Courses (MOOCs), which prompt thousands of users, located all over the world, to present themselves to others, often by posting a message in a forum with information about themselves, their learning goals, and the like. More elaborate scripts may require learners to engage in collaborative or argumentative activities, negotiation of goals and means to attain them, discussion between peers about the quality of productions or interactions, and so on (*ibid*). The common factor shared by all the possible activities is nevertheless the fact that awareness is mainly produced by the *script*, that is, by the learning design itself. 

Group awareness tools [*e.g.*, @buderGroupAwarenessTools2011; @engelmannKnowledgeAwarenessCSCL2009; @janssenCoordinatedComputerSupportedCollaborative2013], often shortened in awareness tools, on the other hand, takes a different and mainly unstructured perspective. Rather than sequencing specific moments or activities during which awareness is enacted, group awareness tools bestow learners the responsibility of producing and consuming information whenever it is considered appropriate and instrumental to the learning activity (*ibid.*). In other words, group awareness tools are usually integrated alongside the learning activity -- persistently or *on demand* -- and support learners in making others aware, as well as becoming aware of others. As stated by Miller and Hadwin [-@millerScriptingAwarenessTools2015. p. 582], compared to scripting tools, "group awareness tools take a more non-directive or reactive approach placing the locus of control in the hands of the learners". 

It is posited here that a group awareness strategy best suits the objectives to convey emotional awareness for the following reasons. First, it potentially minimizes the latency time between emotion experience and expression. Moment-to-moment emotion self-reporting is considered to be more reliable than retrospective self-report, and therefore it is worth endowing learners with the possibility to express their emotions at the very moment they want or can [@fuentesSystematicLiteratureReview2017; @maussMeasuresEmotionReview2009; @ritchieEvolutionSelfreportingMethods2016; @robinsonEpisodicSemanticKnowledge20020619]. The second reason directly follows the first, since a group awareness perspective also potentially minimizes the latency time before emotion information provided by others is perceived. In both cases, the gain in latency time is labeled as potential, because it depends on learners disposition to express or take emotional information into account, both from a situated or personality trait perspectives [@kringIndividualDifferencesDispositional1994; @vankleefHowEmotionsRegulate2009; @pashlerDualtaskInterferenceSimple1994] --- a factor discussed more thoroughly later in the chapter. Third, as already mentioned, the use of group awareness tool can be integrated into a scripting strategy [@millerScriptingAwarenessTools2015], which is consistent with the multipurpose vocation of EAT put forward in the thesis. This is particularly relevant considering that one of the main pitfalls identified in the use of group awareness tools "is taking for granted that social interaction automatically takes place just because an environment makes it technologically possible" [@kreijnsIdentifyingPitfallsSocial2003, p. 336]. For these reasons, the next section delves deeper into the literature about group awareness tools.

### Current Trends in Research on Awareness Tools

As stated in the preamble of the section, group awareness tools, hereafter shortened to awareness tools, are a recent research topic in computer-mediated learning environments, but have a more established tradition in computer-mediated communication and collaboration [@baltesComputerMediatedCommunicationGroup2002; @lickliderComputerCommunicationDevice1968; @fjermestadAnalysisCommunicationMode2004; @dourishAwarenessCoordinationShared1992; @grossUsercenteredAwarenessComputersupported2005; @grudinComputerSupportedCooperativeWork1994]. 

"is the tendency to restrict social interaction to educational interventions aimed at cognitive processes while social (psychological) interventions aimed at socio-emotional processes are ignored, neglected or forgotten" [@kreijnsIdentifyingPitfallsSocial2003, p. 336]

### Synthesis

## The Rationale Behind Emotion Awareness Tools

### Social Functions of Emotion

The social and cultural function of emotion may therefore have been built upon a *feature* that has evolved particularly in some species, such as human beings, for which inter-personal relations are pivotal to survival and, less dramatically, well-being [@parkinsonEmotionSocialRelations2005; @rimePartageSocialEmotions2005; @vankleefInterpersonalDynamicsEmotion2018; @keltnerSocialFunctionsEmotions1999]. Keltner and Haidt [-@keltnerSocialFunctionsEmotions1999] identify four level of analysis in which emotion play a social function: (1) the individual level, whenever the source of the emotion is of a social nature -- which, for some scholars, means most if not all of the time [@fischerWhereHaveAll2010; @parkinsonEmotionsAreSocial1996; @rimeEmotionElicitsSocial2009]; (2) the dyadic level, such as in direct dialogue or collaboration; (3) the group-level, in which people share a common identities and goals to attain; and (4) the cultural level, where the analysis focus on macro-elements such as history and tradition. A recent overarching synthesis on the social function of emotions across all levels proposed by Fischer and Manstead [-@fischerSocialFunctionsEmotion2016] identifies two complementary, but distinct, functions performed by emotions: affiliation, and distancing. The affiliation function serves to form and maintain positive social relationship with others, whereas the distancing function helps in establishing and maintaining a social position relative to others. Other social functions of emotions, further developed below in the chapter, comprise the spontaneous tendency of people to share their emotions with others [@rimeEmotionElicitsSocial2009; @rimePartageSocialEmotions2005], the use of emotional information to better understand behavior and appropriate conduct in social situations [@parkinsonEmotionsInterpersonalInteractions2010; @vankleefHowEmotionsRegulate2009], or situation in which people voluntary attempt to act upon emotions in others [@netzerInterpersonalInstrumentalEmotion2015; @reeckSocialRegulationEmotion2016; @zakiInterpersonalEmotionRegulation2013].

## Methodological Challenges in the Implementation of Emotional Awareness 


## Summary
