# (PART\*) Proof of Concept {.unnumbered}

In Part I of the thesis, the network of theoretical foundations in which the concept of an Emotion Awareness Tool (EAT) is intertwined has been set forth with respect both to the overall affective milieu in which the use of this type of tool is currently investigated, and the challenges in the conceptualization of each of the terms composing the acronym. Emotion has been illustrated through an overarching framework, the Component Process Model, from which a causal mechanisms as been retained: appraisals criteria as determinants of elicitation and differentiation in the emotional experience in the form of a holistic subjective feeling. Awareness has been substantiated in a double perspective: self-awareness and group-awareness, depending on the target of the instrumental information provided by emotional awareness. Finally, the technical part, the Tool, has been circumscribed to a moment-to-moment and self-report perspective. In a nutshell, these are the main premises to two intertwined methodological objectives:

Part II of the thesis will leverage on the theoretical background for the concrete implementation of an Emotion Awareness Tool (EAT). More specifically, this part of the thesis is driven by two methodological objectives:

1.  Endowing computer-mediated learning environments with an EAT that implements an emotional structure as an abstract and parsimonious computational model linking appraisals and subjective feeling as a means to foster emotional self-awareness and/or emotional group-awareness;
2.  Leveraging on this mechanism to provide researchers and instructional designers with a multi-purpose, moment-to-moment, and self-report EAT, which may be adapted to their needs in an open-ended perspective, fostering comparison, sharing, and cumulative knowledge on the subject of emotional awareness in computer-mediated learning environments.

A note regarding Part II of the thesis is nevertheless needed before laying out its contents. Even though the methodological part is illustrated before the empirical contributions of Part III, the overall process has not been straightforward, but rather iterative, following human-computer interaction principles [@mackenzieHumancomputerInteractionEmpirical2013; @rogersInterctionDesignHumanComputer2011]. The technical and methodological implementation of the EAT has both informed, and been informed by, the empirical contributions of Part III. This means that Part II presents the result of the last iterative process, the one that implements data and experience from the empirical contributions. At the same time, some of the technical and methodological elements resulting from the last iteration were not available for the empirical contributions. As a consequence, empirical contributions do not necessarily take full advantage or explore thoroughly all the available features.

The iterative process also determines the use of the term proof-of-concept, since the overall process is to be intended as an attempt to assess to what extent an EAT may emerge with the desired characteristics and fulfill the desired objectives. At the same time, the proof-of-concept perspective highlights the fact that the result is mainly focused on conceptual features, whereas technical and programming issues (e.g., debugging, error-handling, ...) have been considered only to the extent that they were determinant in the development of a minimum viable product.

Finally, to keep this part of the contribution to a manageable length and accessible to non-technical readers, technical and programming information which do not have a clear scientific impact (*e.g.* the inner functioning of the tool) will not be illustrated thoroughly. Interested readers in the technical aspects are encouraged to explore the code and documentation available in the following public repositories:

...

...
