# Methodological Objectives {.unnumbered}

In Part I of the thesis, the dense network of theoretical foundations in which the concept of Emotion Awareness Tool (EAT) is intertwined has been set forth with respect both to the overall *affective milieu* in which the use of this tool is currently investigated, and the challenges in the conceptualization of each of the terms composing the acronym. *Emotion* has been illustrated through an overarching framework, the Component Process Model, and formally defined through a working definition. *Awareness* has been substantiated in a double perspective: self-awareness, and group-awareness. Finally, the technical part, the *Tool*, has been circumscribed to a moment-to-moment and self-report perspective. In a nutshell, these are the main premises to the methodological objectives of the thesis, which are formalized in this foreword to Part II. The objectives can be grouped in two categories: (1) extension of previous work conducted as part of my Master thesis, by abstracting a prototype of an EAT to a flexible, configurable appraisal-driven emotional structure to be implemented by the tool; and (2) leveraging on this very abstraction provided by the proof-of-concept to implement and foster open-science principles by facilitating the possibility to share and compare configuration and data obtained by the EAT. Both objectives are further detailed in the reminder of this foreword. 

## Extension of Previous Work: Abstracting the Dynamic Emotion Wheel 

The overall methodological objective consists in providing a proof-of-concept of an appraisal-driven Emotion Awareness Tool, which can be implemented in research or instructional design interested in endowing computer-mediated learning environments with emotional awareness. To attain this objective, previous work will be extended both theoretically and technically [@fritzDynamicEmotionWheel2015; @fritzDynamicEmotionWheel2016; @fritzProvidingEmotionalAwareness2017; @fritzRealTimeEmotionalAwareness2016; @fritzReinventingWheelEmotional2015]. As part of a *spin-off* of the *Emotion Awareness Tool for Computer-Mediated Interactions* (EATMINT) project [@molinariEmotionFeedbackComputermediated2013], I have designed for my Master thesis [@fritzReinventingWheelEmotional2015] a prototype of EAT, which I named *Dynamic Emotion Wheel* (DEW), for it is deeply inspired by the Geneva Emotion Wheel presented in Part I of the thesis. The DEW was mainly driven by usability concerns emerged with the use of a provisional EAT adopted in the empirical contributions of the EATMINT project [@molinariEmotionFeedbackComputermediated2013]. But, as it is often the case in Human-Computer Interaction, usability issues were just the top of the iceberg of submerged concerns about the implementation of an EAT; concerns that have been further reconsidered and extended in Part I of the thesis.

It is worth noting at this point, in fact, that even though the appraisal-driven EAT developed of an extension of the DEW is presented here before the empirical contribution, the development phase was not straightforward. On the contrary, the iterative process currently adopted in various development...

## Implementing and Fostering Open-Science Principles 