# Foreward to the Empirical Part of the Thesis {.unnumbered}

Part II of the thesis outlined the features of an multipurpose EAT with specific characteristics, which aim at providing learners with a tool that implements an emotion structure in terms of the cognitive evaluation of the situation, from which learners may benefit both in terms of self- and group-awareness. In the meantime, the proposed EAT also aim at providing a viable research tool, that scholars may implement in their research. The empirical part of the thesis therefore attempts to combine the two levels of analysis by (1) investigating the EAT in computer-mediated learning environments with respect to concrete research questions derived from the extant literature in the field; and (2) providing an overall assessment of the EAT with respect to its most characteristics features (appraisal-driven, moment-to-moment, and based on self-report). 

As an attempt to combine the two objectives, Part III of the thesis is organized in three chapters. The next chapter illustrates the first empirical contribution, in which the EAT is implemented in a synchronous and collaborative computer-mediated learning environments, therefore within coordinates that are closer to the use of group-awareness tools in Computer-Supported Collaborative Learning. The following chapter, on the other hand, implements the EAT in an asynchronous and individual computer-mediated learning environment, in conditions that are closer to *mainstream* e-learning settings. The last chapter of Part III takes advantage from the use of the *same* EAT -- even though in different configurations that will be illustrated in the material sections of each chapter -- to propose an overall and comparative assessment of the tool. Alongside specific research questions, thus, there is an overall objective: 

>investigate some factors -- intrinsic to the tool, emerging from the interaction between the learners and the tool, or between the learners themselves -- which may determine the adoption, use and perception of the EAT in computer-mediated learning environments.

It is worth mentioning in this foreword that the empirical contributions of the thesis had to be adapted due to the COVID19 pandemic, which hindered and delayed research at various levels. In particular, a third experiment was planned but could not be carried out. It aimed at determining whether differences in the emotional information available through the EAT modified the perception of the colleague in a computer-mediated collaborative environment above and beyond the available information in the content space of the collaboration. It was meant as a follow-up of the empirical contribution of the next chapter, and was planned with $N = 160$ participants as a result of a power analysis to maximize its informative potential. The experiment will eventually be performed outside the scope of the thesis. Unfortunately, though, the two empirical contributions presented hereafter have less informative potential, and the overall empirical scope of the thesis is therefore limited by this shortcoming. 